### ISSUE TITLE
Lock suggestions page

### ISSUE THREAD

**Issue by samsmith** [DemocracyClub/yournextrepresentative#100]
https://candidates.democracyclub.org.uk/moderation/suggest-lock/
for review of areas with multiple divisions on a single SOPN PDF, it would be useful to have the list of areas in alphabetical order on a single page to avoid repeated searches of the same PDF

**Comment by JoeMitchell** [comment]
I'm very late to this — but did you find candidates.democracyclub.org.uk/posts, which is the way I go about locking — just working my way through a council area alphabetically (or to the extent that a multiple-page-SOPN allows).
