### ISSUE TITLE
Invalidate lock suggesstions when memberships change

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#1008]
## Example 

1. User A reviews and suggests locking a ballot
2. User B (B for bad) adds a fake candidate to that ballot
3. User C sees that user A has suggested locking, and locks the post (without proper double checking)

If at the point user B added the candidate, user A's suggestion was deleted (or in some way marked as for a previous version of the memberships) then user C wouldn't be asked to review an out of date suggestion.

## Implementation

This related to #1116. We should calculate a hash of all the information on a ballot that we lock (name, party, list position) and store that on the ballot somewhere (or as a property on the model). 

When a ballot is changed, we should delete all lock suggestions for that ballot that don't match the calculated hash.

**Comment by symroe** [comment]
This is especially likely when User C has reviewed a lot of user A's suggestions and knows them to be trustworthy and reliable.

**Comment by michaeljcollinsuk** [comment]
As part of this, would it be unreasonable to remove all existing suggested locks at the point that the ballot is updated? E.g. [here](https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/bulk_adding/views/sopns.py#L226) before the new suggestion is created? I feel like this would mitigate the scenario the scenario outlined above where User C sees the original User A suggestion and is more trustworthy than they would be if they saw just the new suggestion from User B.
