### ISSUE TITLE
Review edge cases for speaker seeking re-election

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#1014]
Next GE we will have a new speaker. Make sure none of the handling for the "speaker seeking re-election" edge cases is in any way tied to Buckingham / E14000608 and will transfer to the new speaker's constituency.

**Comment by symroe** [comment]
I've had a dig about, and I've not found anything that relates to this.

We model the speaker as a "party", so all the special case code is hooked on the party ID, not the person ID or Post ID. 👍
