### ISSUE TITLE
Other names delete button not working

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1020]
Delete button does nothing, e.g. https://candidates.democracyclub.org.uk/person/62384/other-names

![image](https://user-images.githubusercontent.com/10633357/65316379-c1392780-db91-11e9-98e3-20f2f0dfe8d3.png)

**Comment by sjorford** [comment]
This seems to be fixed in the redesign of the `/other-names` screen 👍

**Comment by symroe** [comment]
Oh yeah, forgot to close this when I merged #1075 👍
