### ISSUE TITLE
Convert LoggedAction.action_type to an enum

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#1022]
`action_type` on `LoggedAction` is a CharField with no validation. 

We use the values in that field in various places, including templates. 

That we don't have a comprehensive list of the values without grepping the code could cause problems.

It would be better to have an enum or list of some sort on the model.

**Comment by symroe** [comment]
This should be a `models.TextChoices` class, as described here:  https://stackoverflow.com/questions/54802616/how-to-use-enums-as-a-choice-field-in-django-model

**Comment by VirginiaDooley** [comment]
Resolved with https://github.com/DemocracyClub/yournextrepresentative/pull/1596
