### ISSUE TITLE
GLA Additional members not imported

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#1025]
https://elections.democracyclub.org.uk/elections/gla.a.2020-05-07/
https://candidates.democracyclub.org.uk/elections/gla.a.2020-05-07/

**Comment by symroe** [comment]
Reckon this one can be closed as we have candidates listed against this election currently?

**Comment by chris48s** [comment]
Yeah definitely close it now its working. At the time I posted this, https://candidates.democracyclub.org.uk/elections/gla.a.2020-05-07/ was an error page.
Any idea what changed?

**Comment by symroe** [comment]
Oh, looks like this changed!

https://github.com/DemocracyClub/yournextrepresentative/commit/3b530a7911d297ea2f141dfff406d8ce611e2eef

I guess I forgot to link up the issue
