### ISSUE TITLE
2015 data download listed under 2010

### ISSUE THREAD

**Issue by Floppy** [DemocracyClub/yournextrepresentative#103]
On https://candidates.democracyclub.org.uk/help/api, the 2015 candidate data download is listed under the 2010 list: 

![screen_shot_2017-04-20_at_08 45 25_360](https://cloud.githubusercontent.com/assets/3565/25220205/f72bc704-25a8-11e7-8f1c-8222dd0de77d.png)

@andylolz reckons this is an error in `Election.group_and_order_elections` (https://github.com/DemocracyClub/yournextrepresentative/blob/12aff56a/elections/models.py#L99-L176) somewhere.

**Comment by andylolz** [comment]
Thanks @Floppy!

[This bit of code](https://github.com/DemocracyClub/yournextrepresentative/blob/12aff56a/elections/models.py#L212-L216) starts a new grouping when e.g. the current election and previous election are for different roles. In this case, the role is the same (Member of Parliament) but the date is different. So the linked bit of code should also compare the date of the current and previous election, and start a new grouping when these differ.

Also worth noting that [the example in this docstring](https://github.com/DemocracyClub/yournextrepresentative/blob/12aff56a/elections/models.py#L99-L176) is wrong, which is quite confusing!
