### ISSUE TITLE
candidates_add_twitter_images_to_queue should not requeue already moderated images

### ISSUE THREAD

**Issue by mhl** [DemocracyClub/yournextrepresentative#105]
At the moment, the logic in this command: https://github.com/DemocracyClub/yournextrepresentative/blob/4eb2a85ae656dad3a0d9c2d726bc0ed624cf9d55/candidates/management/commands/candidates_add_twitter_images_to_queue.py isn't quite right, which is stopping us from running it every night (which was the intention). The problem is that if a photo imported on a previous night was moderated and accepted, it will still be added to the queue by this command.

The simplest solution is probably to only queue the image if the candidate has no `Image`s associated with them and they have no `QueuedImage`s in the queue (regardless of whether they were accepted or rejected - the `QueuedImage` objects aren't ever deleted regardless of the decision made about them - the `decision` field is just set). That won't queue changed images from candidates, which would be nice, but this fix would be really quick and let us start running the import every night again.

**Comment by symroe** [comment]
Yes that's a nice quick win. I was thinking about calculating the MD5 of the image and storing that in the DB, like we do for party emblems. That wouldn't be a huge amount of extra work, but I agree that this is a better first start (given time is limited)
