### ISSUE TITLE
‘Manchester, Gorton’ by-election name should be expanded

### ISSUE THREAD

**Issue by andylolz** [DemocracyClub/yournextrepresentative#107]
Election names should include the type of election, not just the location. Otherwise it’s weird when used in context, e.g.:
![screen shot 2017-04-20 at 16 21 02](https://cloud.githubusercontent.com/assets/464193/25238452/653eed2a-25e5-11e7-8dc5-0d16428cf224.png)

The Sheffield Brightside by-election is called:
“Sheffield by-election: Sheffield Brightside and Hillsborough constituency”

Also, there’s probably a case for using the `current="Don’t know"` status here [1].

[1]: http://www.bbc.co.uk/news/uk-england-manchester-39635070

**Comment by mhl** [comment]
This is the same issue as: https://github.com/DemocracyClub/yournextrepresentative/issues/67 I think

**Comment by andylolz** [comment]
You’re quite right! Closing!
