### ISSUE TITLE
Uploaded images are being overwritten

### ISSUE THREAD

**Issue by mhl** [DemocracyClub/yournextrepresentative#1096]
These examples were pointed out by jonathanf, Peter and Joe on Slack. If you look at the existing images for:

https://candidates.democracyclub.org.uk/moderation/photo/review/18233

... they're all the same image, but originally were different based on the descriptions and screenshots from jonathanf. It seems that approving a new uploaded image of a candidate is overwriting all of the existing ones. (See `select * from people_personimage where person_id = 23660;` - note that the `image` column is the same for all three images.)

Another example of this problem is in the `moderation_queue_queuedimage` table. Values in the `image` column should be unique, but there are 91 cases where they're not:

```
select id, person_id, decision, image, user_id, created, updated
  from moderation_queue_queuedimage where image in (
    select image from moderation_queue_queuedimage group by image having count(*) > 1
  )
  order by updated;
```

I think this happens when a user uploads an image with the same local basename as another image in the queue on the same day.

The thing in common here is that both of these columns are based on a Django `ImageField`, which uses whatever's set in `DEFAULT_FILE_STORAGE` as the Django storage backend - by default this is `django.core.files.storage.FileSystemStorage`, and still is for local development. However, as of https://github.com/DemocracyClub/YNR_deploy/commit/7ae5b0e1aa1a69b5b470403f9b831006c49e911c the deployed version is using
```
DEFAULT_FILE_STORAGE = 'ynr.s3_storage.MediaStorage'
```
... which is based on storages.backends.s3boto3.S3Boto3Storage. Slightly extraordinarily, this package will overwrite files by default, unless you set `AWS_S3_FILE_OVERWRITE = False`, and that's not being done at the moment. So the storage backend isn't generating unique filenames if you try to store a file with the same desired path.

I can't see if versioning is enabled for this s3 bucket, or if there are any backups, but it looks at the moment as if candidate images are being lost at the moment because of this misconfiguration.

I'll make a PR to add this setting.

**Comment by chris48s** [comment]
Looking at the S3 bucket in AWS console, it does not have versioning enabled so any we've already overwritten are lost :(

**Comment by mhl** [comment]
> Looking at the S3 bucket in AWS console, it does not have versioning enabled so any we've already overwritten are lost :(

Oh dear :(

I may have an old copy of the media directory in my backups from before storage was moved to s3 but that would be very old now. If anyone ran the live site importer recently, that should have download the approved candidate images as well - @symroe would be most likely to have one, I think, since he's been working on that code.
