### ISSUE TITLE
Data issue: Add a past (contested) election for Stuart Jeffery

### ISSUE THREAD

**Issue by andylolz** [DemocracyClub/yournextrepresentative#110]
https://candidates.democracyclub.org.uk/person/2111

The following candidacy (and result) is missing:
> [Shepway South ward](https://candidates.democracyclub.org.uk/election/local.maidstone.2016-05-05/post/DIW:E05005004/shepway-south-ward) Green Party – Maidstone local election
> Not elected (25 votes).

(I broke this, sorry!)

**Comment by symroe** [comment]
Sorry this took a while to fix, I've done it now!
