### ISSUE TITLE
Deceased candidate shown as standing down

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1110]
Where an elected candidate has died, they are shown as "standing down" against the resulting by-election

e,g. https://candidates.democracyclub.org.uk/person/32236

![image](https://user-images.githubusercontent.com/10633357/68996753-35dcc980-0896-11ea-988c-c8d570501620.png)

**Comment by chris48s** [comment]
second example of this: https://candidates.democracyclub.org.uk/person/4024/

**Comment by sjorford** [comment]
Still seems to be an issue on https://candidates.democracyclub.org.uk/person/61750/frederick-barnes

![image](https://user-images.githubusercontent.com/10633357/74916711-3f5a5e00-53be-11ea-9338-375c4cd4f95e.png)

I think this is because he was explicitly listed as standing down on the ballot page: https://candidates.democracyclub.org.uk/elections/local.stratford-on-avon.welford-on-avon.by.2020-03-12/

**Comment by symroe** [comment]
Ah, I'd not deployed this – have done so now and looks fixed.
