### ISSUE TITLE
Council By-Election Missing

### ISSUE THREAD

**Issue by PoliceSheep** [DemocracyClub/yournextrepresentative#1111]
Wycombe District Council - Disraeli
https://councillors.wycombe.gov.uk/mgElectionAreaResults.aspx?ID=69

**Comment by pmk01** [comment]
I assume this refers to the 2013 by-election, in which case it predates our local elections database. We have decided not to add historic local elections at this stage. 
https://www.wycombe.gov.uk/pages/About-the-council/Elections-and-voting/By-elections.aspx
