### ISSUE TITLE
Incorrect election results

### ISSUE THREAD

**Issue by PoliceSheep** [DemocracyClub/yournextrepresentative#1115]
https://candidates.democracyclub.org.uk/elections/local.city-of-london.billingsgate.by.2018-03-22/

John Michael Allen-Petrie should be shown as elected.

https://www.citymatters.london/john-allen-petrie-wins-billingsgate-election/

**Comment by sjorford** [comment]
Another that seems to have the same issue - Danis Rixson should be marked as elected

https://candidates.democracyclub.org.uk/elections/local.highland.caol-and-mallaig.by.2018-04-05/

**Comment by symroe** [comment]
It should now be possible to fix these (I'm not sure what the initial problem was) by changing going to `https://candidates.democracyclub.org.uk/uk_results/<ballot_id>/` and pressing save on that page (assuming the numbers are correct).
