### ISSUE TITLE
Prevent entering partial result sets

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1147]
One user entered a number of partial results (usually only Con/Lab/LD) for GE2019, e.g. https://candidates.democracyclub.org.uk/uk_results/parl.east-worthing-and-shoreham.2019-12-12/

The results form should prevent saving partial results, or at least throw a warning to encourage the user to find the missing values

**Comment by symroe** [comment]
Interesting!

I made the change to allow partial results just before this election, as I assumed "X won with xx,000 votes" would be easy to find / enter than the full results. People seemed keen to enter these partial results.

If a partial result is entered, winners aren't set automatically. Maybe we need some way of filtering results by incomplete?

Or do you think it's better to just abandon this feature and force full entry?

**Comment by sjorford** [comment]
I guess it's fine to allow partial results to be entered if that's all we have - best not to discourage people who are trying to help - although in practice all the full results were available from other sources. 

It wasn't showing up on the front page though - so we had "Results entered - Yes" against a bunch of constituencies where it should probably say "Partial results only - please find the full result!"

**Comment by michaeljcollinsuk** [comment]
Closed by #1474
