### ISSUE TITLE
Elections on an area page should be ordered soonest first

### ISSUE THREAD

**Issue by andylolz** [DemocracyClub/yournextrepresentative#116]
E.g. Here:
https://candidates.democracyclub.org.uk/areas/CED--CAM:market,WMC--gss:E14000617,combined-authority--combined-authority:cambridgeshire-and-peterborough

The posts shown fall on the dates: 4 May, 8 June, 4 May. I guess GE2017 should be shown third.

**Comment by jf1** [comment]
+1 for sort:ASC in the above case, however it'd be better as sort:DESC here: https://candidates.democracyclub.org.uk/help/api

It lists current then previous CSVs in a non-linear way:
Current Elections (should that be future elections?) 
May 4, 2017
May 11, 2017
June 8, 2017
Past Elections (should the display have 'recent' elections for those within the last 30 days?)
May 6, 2010
May 7, 2015
May 5, 2016

This would be more logical for me if, on May 5-10 2017. the display was:
Future Elections
June 8, 2017
May 11, 2017
Recent Elections:
May 4, 2017
Past Elections:
May 5, 2016
May 7, 2015
May 6, 2010

**Comment by andylolz** [comment]
Ah, that’s a much better suggestion!
