### ISSUE TITLE
Error 500 marking as not standing

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1178]
e.g. on https://candidates.democracyclub.org.uk/elections/gla.a.2020-05-07/ marking Scott Ainslie as not standing throws Server Error 500

Also got the same error on Gulnar Hasnain - marking her as not standing on the candidate page worked fine.

See previously #878 and #143 which may or may not be related

**Comment by sjorford** [comment]
Another case of this - https://candidates.democracyclub.org.uk/person/1730/flick-drummond

Getting `500` errors when I mark her as not standing in `pcc.hampshire.2020-05-07`, both on the post page and the candidate page.

**Comment by symroe** [comment]
I've just edited https://candidates.democracyclub.org.uk/person/1730 and marked her as not standing. I reckon this is fixed?

**Comment by sjorford** [comment]
Yep, sounds fixed.
