### ISSUE TITLE
The 2019 General Election results CSV no longer has GSS codes in the gss column

### ISSUE THREAD

**Issue by mhl** [DemocracyClub/yournextrepresentative#1181]
https://candidates.democracyclub.org.uk/results/csv/parl.2019-12-12/ seems to now have constituency slugs instead of GSS codes in the `gss` column. I think this is probably due to the change in this PR https://github.com/DemocracyClub/yournextrepresentative/pull/1168/ which means that this line no longer extracts the gss code: https://github.com/DemocracyClub/yournextrepresentative/blob/ca3bca6f9b7a89dbd23051dd6fbf26d70cc2fc5f/ynr/apps/uk_results/views/base_views.py#L155

**Comment by mhl** [comment]
Thanks for looking at this, but I think this fix may not have worked:

```
$ curl -s 'https://candidates.democracyclub.org.uk/results/csv/parl.2019-12-12/' | q -d, -H 'select gss from - limit 3'
north-down
newcastle-under-lyme
windsor
```

**Comment by chris48s** [comment]
I think there's a separate issues with CSVs either not being generated or not being synced to S3 in production.

I think the fix in f8387f7 should fix the _code_ , so if you generate that CSV locally it would be right, but the CSVs being served in production are still wrong/stale for a different reason. Its the same problem as https://github.com/DemocracyClub/yournextrepresentative/pull/1177#issuecomment-586205469

..probably

**Comment by mhl** [comment]
@chris48s Thanks for replying. Are you sure this path is being served from S3, though? I can see the request is a cloudfront miss and then a suspiciously long time to return the file, as if it is being generated on demand by Django.

(Unfortunately, I can't run this locally, since my local database is very stale, and `candidates_import_from_live_site` is broken at the moment, I think.)

**Comment by symroe** [comment]
Sorry Mark, I forgot to apply the same fix to the parl CSV. I don't know what the `q` command is in your example above, but I think it should be working now. Can you confirm?

**Comment by mhl** [comment]
Thanks, @symroe - it works now!

(`q` was the very useful http://harelba.github.io/q/ for querying CSV files with SQL.)

**Comment by symroe** [comment]
> q was the very useful 

Thanks, I'll investigate!
