### ISSUE TITLE
Reverting to an earlier version can remove locked post candidacies

### ISSUE THREAD

**Issue by andylolz** [DemocracyClub/yournextrepresentative#121]
The version history for https://candidates.democracyclub.org.uk/person/2111/stuart-jeffery includes the following revert:
![screen shot 2017-04-23 at 20 18 22](https://cloud.githubusercontent.com/assets/464193/25316615/5068da62-2862-11e7-8f5e-c659e5164dad.png)

`local.maidstone.2016-05-05` was a locked post at the time of performing the reversion, so perhaps I should have been prevented from performing the operation.

Refs #118.

**Comment by jf1** [comment]
+1 especially as any registered user has the power to revert.

As a temporary fix could the revert privilege only be available to users with some other non-standard privilege, with a 'suggest reverting to this version' option for basic users?

**Comment by symroe** [comment]
This was fixed in #1036
