### ISSUE TITLE
Link cancelled elections and replacements

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1222]
There should be a link on https://candidates.democracyclub.org.uk/elections/mayor.greater-manchester-ca.2020-05-07/ pointing to https://candidates.democracyclub.org.uk/elections/mayor.greater-manchester-ca.2021-05-06/ and vice versa - this would be especially useful this year given the large number of rescheduled elections.

**Comment by symroe** [comment]
e.g at the top of https://candidates.democracyclub.org.uk/elections/gla.c.croydon-and-sutton.2021-05-06/
