### ISSUE TITLE
Search doesn't find name variants

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1227]
e.g. https://candidates.democracyclub.org.uk/search?q=Dan+Gallagher finds Dan but not Daniel:
![image](https://user-images.githubusercontent.com/10633357/95085589-56647b00-0717-11eb-879f-4ea9d19cb806.png)

https://candidates.democracyclub.org.uk/search?q=Daniel+Gallagher is vice versa:
![image](https://user-images.githubusercontent.com/10633357/95085631-64b29700-0717-11eb-9974-16aaf8946c3f.png)

This seems to be pretty consistenty the case with name variants that are substrings of the full name (Phil/Phillip, Steve/Steven, Pete/Peter) but it also fails to match cases like Jim/James, Mike/Michael etc.

**Comment by symroe** [comment]
Interesting.

I've changed the search a bit recently, did this used to work?

Do you know of a good synonym database for English language names?

**Comment by sjorford** [comment]
I think it used to be better - when looking for merges (working off the CSV) I'm sure I used to be able to pick up both pages with a single search a lot of the time, and now most of the time I need to search twice.

It does seem particularly keen to match the first name exactly - e.g. searching for "Shaun Stephenson" finds https://candidates.democracyclub.org.uk/person/50019/shaun-stephenson-mcgall but not https://candidates.democracyclub.org.uk/person/53673/sean-stephenson-mcgall

https://twitter.com/hashtag/shaunandsean 💘

**Comment by sjorford** [comment]
I don't know of a good database of name synonyms - it might be possible to build a simple one by comparing the Name and Alternative Name fields in the database already?

**Comment by sjorford** [comment]
Related: search doesn't seem to pick up alternate names either

e.g. "Elizabeth Pole" doesn't find https://candidates.democracyclub.org.uk/person/66242/liz-pole but that is an aka on that page

**Comment by symroe** [comment]
@sjorford I've deployed some changes that address some of these issues:

1. We now search alternative names, but we rank matches against other names lower than the "main" name field
2. We support name synonyms, although none are currently in the database

We don't (currently) support typo or misspellings - it's hard to know if this is a good idea, as getting fuzzy with spelling might just lower the accuracy of the results for every search.

Please let me know if you spot any problems, or even improvements! ;)

**Comment by sjorford** [comment]
Noticing a few cases where name searches fail to find exact matches - don't know if these are just temporary, but these currently fail:

https://candidates.democracyclub.org.uk/search?q=Will+Coles
fails to find
https://candidates.democracyclub.org.uk/person/33510/will-coles
https://candidates.democracyclub.org.uk/person/83475/will-coles
![image](https://user-images.githubusercontent.com/10633357/115602092-72f08b00-a2d6-11eb-8865-d47324098593.png)

https://candidates.democracyclub.org.uk/search?q=Tony+Over
fails to find
https://candidates.democracyclub.org.uk/person/56233/tony-over
![image](https://user-images.githubusercontent.com/10633357/115602324-b77c2680-a2d6-11eb-9b7c-ced7ec2fcfd5.png)

**Comment by sjorford** [comment]
And another - Sam Down
https://candidates.democracyclub.org.uk/person/17594/sam-down
https://candidates.democracyclub.org.uk/person/80679/sam-down

![image](https://user-images.githubusercontent.com/10633357/116723785-c0a47c00-a9d7-11eb-8394-2c3322e39cb7.png)

Don't know if it's significant, but all the examples so far are short names?

**Comment by symroe** [comment]
I've been through all of these cases and I think they're all sorted now. I'll close this issue, but please re-open if I've missed anything!
