### ISSUE TITLE
Can't edit alternate names notes field

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1242]
If you try and edit an alternate name and just change the note text, the change is rejected as a duplicate:

![image](https://user-images.githubusercontent.com/10633357/99361593-3beef700-28aa-11eb-82ad-ed0ef6a1c7e0.png)

**Comment by symroe** [comment]
@sjorford this should have been fixed - can you confirm please?

**Comment by sjorford** [comment]
Yes seems fixed https://candidates.democracyclub.org.uk/person/4359/nik-johnson
