### ISSUE TITLE
Don't show existing elections for candidate in dropdown

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1283]
If a candidate is already standing in e.g. `sp.c.2021.05.06`, you can still select `sp.c.2021.05.06` from the "Add a new election" dropdown. Selecting it election partly clears the existing candidacy, and you end up with two "Standing in" inputs.

![image](https://user-images.githubusercontent.com/10633357/101453122-bc8f9900-3926-11eb-90af-cc9c23334504.png)

![image](https://user-images.githubusercontent.com/10633357/101452906-61f63d00-3926-11eb-879c-d93e93087c25.png)

**Comment by symroe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Don't show existing elections for candidate in dropdown](https://trello.com/c/UtPAsN0C/3143-dont-show-existing-elections-for-candidate-in-dropdown)
