### ISSUE TITLE
Photo approval page no longer identifies faces

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1335]
It used to be really good at this, but now never seems to pick out the face - here are a few from the current queue:

![image](https://user-images.githubusercontent.com/10633357/108766582-3f4eea00-754d-11eb-82c3-845af89650b6.png)
![image](https://user-images.githubusercontent.com/10633357/108766614-4970e880-754d-11eb-9f47-747c46baddef.png)
![image](https://user-images.githubusercontent.com/10633357/108766651-55f54100-754d-11eb-8e7d-5c8b32eeac65.png)
![image](https://user-images.githubusercontent.com/10633357/108766687-60afd600-754d-11eb-9101-cb42133bc3ef.png)

**Comment by VirginiaDooley** [comment]
Closed with https://github.com/DemocracyClub/yournextrepresentative/pull/1776
