### ISSUE TITLE
Store Party name and Description used on Membership

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#1347]
When adding candidates, especially from SOPNs, we ask users to pick a party from a drop down.

This drop-down includes the registered descriptions, and the type-ahead picks them up. This is because if you have an obscure description on the SOPN it can be hard to know what the party actually is - for example "Bringing Democracy to the People" is a description of the "21st Century Democracy" party. It's possible the SOPN only contains the description, leaving most people with no clue what party to pick.

However, we only use this input to resolve to a party, and we then discard it. 

What we should do is modify the `Membership` model to store the entered description text, and also add a FK to the `PartyDescription`.

The reason to add the text as well as the `fk` is that this information might change over time, and we need to keep the historic record.

As for the party name, see https://github.com/DemocracyClub/yournextrepresentative/issues/1303 for more information. In short, we need to store the party name at the time of nomination on the `Membership` model, next to the description.

**Comment by VirginiaDooley** [comment]
@symroe Should the form to add individual candidates one by one also feature the party description?

**Comment by symroe** [comment]
Yes, but by work on https://github.com/DemocracyClub/yournextrepresentative/pull/1348 will end up with a massive merge conflict it you try to add it now. 

For the moment, let's focus on the model changes and adding the data from the bulk-adding process - we can add the description on the person add/edit forms later.
