### ISSUE TITLE
Party emblems

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/yournextrepresentative#1353]
The reform party emblem needs to be updated, and the Lab/Co-op one added.

More broadly, a way to pick which registered emblem we use on candidates (maybe via admin?) would be a useful feature.

**Comment by symroe** [comment]
To change the _default_ emblem, we need the ID on the EC's site. We can then add it to this list:

https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/parties/constants.py#L18

The problem with being able to change the emblem _per candidate_ is that there are no public sources of the emblem that a candidate will be using. Of course candidates can tell us, but that's not very scalable. If we add this feature, I'd want it to be part of the public editing interface, so at least they can fix it themselves.

**Comment by pmk01** [comment]
Yes, I meant to say change the default emblem for all parties. Though perhaps this needs a wider conversation about party info on YNR.

**Comment by pmk01** [comment]
All for Unity's emblem is also broken.

**Comment by pmk01** [comment]
Neither Reform UK's emblem is not Candidates.
https://candidates.democracyclub.org.uk/person/74477/catherine-elizabeth-mary-mount

All 4 Unity's is.
https://candidates.democracyclub.org.uk/person/74469/paul-burrows

**Comment by pmk01** [comment]
Sorry, reopening this. The Newcastle Independents want their changed to Emblem 2.

http://search.electoralcommission.org.uk/Registrations/PP905
