### ISSUE TITLE
Some party descriptions not pre-selected on bulk adding page after Sopn parsing has completed successfully

### ISSUE THREAD

**Issue by michaeljcollinsuk** [DemocracyClub/yournextrepresentative#1367]
### Issue and Steps to Reproduce
After SOPN parsing, if the party description found for a candidates is not within the initial list of displayed Party Description options displayed on the Bulk Add form, the description is not pre-selected and instead appears as None. For example, parsing a candidate for the All People's Party, the description object was found and correctly stored in the RawPeople data, but is not selected on the bulk add page. I think this is due to the party options that are initially being limited to more common parties.

### Screenshots
<img width="1000" alt="Screenshot 2021-03-18 at 17 11 34" src="https://user-images.githubusercontent.com/15347726/111668371-9757d400-880d-11eb-95d9-3a3a60bcd2e2.png">

#### Expected
The All People's Party would have been pre-selected

#### Actual
No party is selected

**Comment by symroe** [comment]
This is likely to be fixed as part of #1348 - but good catch, I'll make sure I test it

**Comment by michaeljcollinsuk** [comment]
@symroe this still seems to be occurring - seems more prevalent in fact as now "Independent" is not pre-selected

**Comment by jf1** [comment]
The only regular error I'm aware of at the moment is when a party description rolls over onto a second line within the same cell, then the parser doesn't match it to a stored description.

As well as seeing this caused by party descriptions being split on spaces, I've also noticed a couple that were split on the `-` in `Co-operative`

**Comment by VirginiaDooley** [comment]
This is still an issue, at least for `gla.c.city-and-east.2016-05-05`. I think recent changes to matching party descriptions have improved this issue but not solved it. I also checked this ballot on https://github.com/DemocracyClub/yournextrepresentative/pull/1712 and it's still a problem. I think All People's Party may be an issue in itself, but other parties fail to match on the initial bot parse, but are found once the user clicks 'to load more parties'.

**Comment by michaeljcollinsuk** [comment]
> This is still an issue, at least for `gla.c.city-and-east.2016-05-05`. I think recent changes to matching party descriptions have improved this issue but not solved it. I also checked this ballot on #1712 and it's still a problem. I think All People's Party may be an issue in itself, but other parties fail to match on the initial bot parse, but are found once the user clicks 'to load more parties'.

I forgot to open this [PR](https://github.com/DemocracyClub/yournextrepresentative/pull/1730) before I was off ill last week. I think this closes the issue, but going to do some extra testing before merging

**Comment by michaeljcollinsuk** [comment]
@VirginiaDooley confirmed that after successful parsing, the party is then loaded on the bulk add form without the need to click the "Load more parties" link
![Screenshot 2022-01-31 at 17 12 18](https://user-images.githubusercontent.com/15347726/151840464-9d16ea5b-83c9-4fc1-8e40-deeaffab093e.png)
