### ISSUE TITLE
Tooling for batch testing of SOPN parsing

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#1377]
We don't want to test _loads_ of SOPNs on the normal test runs, but it would be nice to be able to point a script at a few 100 SOPNs and expected data to make sure that changes to the SOPN parsing code doesn't end up breaking stuff.

This would look like a management command that runs the tests over ~500 previous SOPNs and checks that are are all parsed as expected

**Comment by symroe** [comment]
After a chat with @VirginiaDooley about this, we decided on a first version implementation that will provide a decent "smoke test":

1. Use the API to download a load of SOPNs. We can get this from the `/ballots/` endpoint
2. For each SOPN, also create a JSON file that represents that ballot, containing (at the moment) a structure like: 
    ```json
    {
      "candidacies": [
        {"party": "PP52__392"},
        {"party": "PP51__322"},
      ]
    }
    ```
3. We then parse the SOPN and check that the number of candidacies parsed is the same as the length of the `candidacies` key, and that all the parties are matched correctly.
4. For the moment, we'll exclude checking names, as they can be changed from the SOPN values

**Comment by symroe** [comment]
Thinking about this a little more, we might need to group the SOPNs by election and store the source URL for each. This would allow us to populate the test database in a much more realistic way.

**Comment by michaeljcollinsuk** [comment]
> After a chat with @VirginiaDooley about this, we decided on a first version implementation that will provide a decent "smoke test":
> 
> 2. For each SOPN, also create a JSON file that represents that ballot, containing (at the moment) a structure like:
>    ```json
>    {
>      "candidacies": [
>        {"party": "PP52__392"},
>        {"party": "PP51__322"},
>      ]
>    }
>    ```

Should this json structure be built from parsing the downloaded SOPN or from the candidacies data from the API? Because the data from the API doesn't necessarily mean that they were parsed from the file does it?

E.g. if parsing failed when it was uploaded, and the candidates had to be added manually, when we download it and parse it in our tooling and check the number of candidates, it will look like we might have broken something but actually it had never worked in the first place.

**Comment by symroe** [comment]
It's true there will be some error rate on the first run (before changing anything....we could in theory try this on the version of the code before we started changing the page number stuff).

The main thing we want from this it to make sure it's not getting _worse_. So, we can get a baseline, start making changes, and then re-run this set of tests and compare.

Also, it's a nice way to get a full list of all the SOPNs we _can't_ parse.

**Comment by michaeljcollinsuk** [comment]
Yes I agree making sure we dont make anything worse is the key, so I think running the tooling on the commit where master is before any new changes are made would be sensible.
