### ISSUE TITLE
Candidates in May 21 missing list positions

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1391]
Editing a candidate on a locked list ballot, e.g. https://candidates.democracyclub.org.uk/person/74480/christina-mary-hendry

![image](https://user-images.githubusercontent.com/10633357/113275966-3d5c1180-92d7-11eb-9e43-2e4b7a705496.png)

In edit mode, the election name appears but the editable fields are hidden - except the list position field, which is missing:

![image](https://user-images.githubusercontent.com/10633357/113276012-4d73f100-92d7-11eb-819b-d27512c69138.png)

![image](https://user-images.githubusercontent.com/10633357/113276059-5bc20d00-92d7-11eb-8024-03930887c97d.png)

Make a change (e.g. add Twitter handle) and save - the list position is deleted:

![image](https://user-images.githubusercontent.com/10633357/113276293-9d52b800-92d7-11eb-8ac2-688ccbcf4705.png)

![image](https://user-images.githubusercontent.com/10633357/113276318-a2b00280-92d7-11eb-82f3-f6c25604d6ba.png)

**Comment by pmk01** [comment]
Can confirm this, eg https://whocanivotefor.co.uk/elections/sp.r.highlands-and-islands.2021-05-06/party:90/

**Comment by symroe** [comment]
I've deployed some major refactors of the person add / edit system (this might break other things), but I'm fairly sure it will fix this bug.

Here are all the people standing in a locked list election in May 2021 who don't have a list position:

## [gla.a.2021-05-06](https://candidates.democracyclub.org.uk/elections/gla.a.2021-05-06/)
* [ ] [Brilant Krasniqi](https://candidates.democracyclub.org.uk/person/74759/brilant-krasniqi)
* [ ] [John Stevens](https://candidates.democracyclub.org.uk/person/3403/john-stevens)
* [ ] [Julian Weisman](https://candidates.democracyclub.org.uk/person/74741/julian-weisman)
* [ ] [Korina Holmes](https://candidates.democracyclub.org.uk/person/73427/korina-holmes)
* [ ] [Mark Scott](https://candidates.democracyclub.org.uk/person/74740/mark-scott)
* [ ] [Robert Poll](https://candidates.democracyclub.org.uk/person/74148/robert-poll)
* [ ] [Sophie Charman-Blower](https://candidates.democracyclub.org.uk/person/74813/sophie-charman-blower)
## [sp.r.central-scotland.2021-05-06](https://candidates.democracyclub.org.uk/elections/sp.r.central-scotland.2021-05-06/)
* [ ] [Allyson Black](https://candidates.democracyclub.org.uk/person/22555/allyson-black)
* [ ] [Dawn Marion Ferguson Allan](https://candidates.democracyclub.org.uk/person/74623/dawn-marion-ferguson-allan)
* [ ] [Leo Lanahan](https://candidates.democracyclub.org.uk/person/74581/leo-lanahan)
* [ ] [Michelle Thomson](https://candidates.democracyclub.org.uk/person/5922/michelle-thomson)
* [ ] [Paddy Hogg](https://candidates.democracyclub.org.uk/person/22161/paddy-hogg)
* [ ] [Sandra Hill](https://candidates.democracyclub.org.uk/person/74559/sandra-hill)
## [sp.r.glasgow.2021-05-06](https://candidates.democracyclub.org.uk/elections/sp.r.glasgow.2021-05-06/)
* [ ] [Anna Nordahl](https://candidates.democracyclub.org.uk/person/74315/anna-nordahl)
* [ ] [Craig Ross](https://candidates.democracyclub.org.uk/person/72956/craig-ross)
* [ ] [Dan Hutchison](https://candidates.democracyclub.org.uk/person/71801/dan-hutchison)
* [ ] [Danield Donaldson](https://candidates.democracyclub.org.uk/person/74450/danield-donaldson)
* [ ] [Daryl Gardner](https://candidates.democracyclub.org.uk/person/22183/daryl-gardner)
* [ ] [Esthi Thurston](https://candidates.democracyclub.org.uk/person/74314/esthi-thurston)
* [ ] [James Matthew Maxwell Dunsmore](https://candidates.democracyclub.org.uk/person/74399/james-matthew-maxwell-dunsmore)
* [ ] [James Speirs](https://candidates.democracyclub.org.uk/person/6962/james-speirs)
* [ ] [Joe McCauley](https://candidates.democracyclub.org.uk/person/73503/joe-mccauley)
* [ ] [Kim Long](https://candidates.democracyclub.org.uk/person/6018/kim-long)
* [ ] [Leo Kearse](https://candidates.democracyclub.org.uk/person/74446/leo-kearse)
* [ ] [Paul John Laird](https://candidates.democracyclub.org.uk/person/74424/paul-john-laird)
* [ ] [Ruth Victoria Wilkinson](https://candidates.democracyclub.org.uk/person/8389/ruth-victoria-wilkinson)
* [ ] [Stephen Robert Lonsdale](https://candidates.democracyclub.org.uk/person/74411/stephen-robert-lonsdale)
* [ ] [Suzanne Martin](https://candidates.democracyclub.org.uk/person/74313/suzanne-martin)
## [sp.r.highlands-and-islands.2021-05-06](https://candidates.democracyclub.org.uk/elections/sp.r.highlands-and-islands.2021-05-06/)
* [ ] [Andy Wightman](https://candidates.democracyclub.org.uk/person/7484/andy-wightman)
* [ ] [Brian Nugent](https://candidates.democracyclub.org.uk/person/21017/brian-nugent)
* [ ] [Emma Alice Idzikowska](https://candidates.democracyclub.org.uk/person/74473/emma-alice-idzikowska)
* [ ] [Harry Christian](https://candidates.democracyclub.org.uk/person/22627/harry-christian)
* [ ] [Hazel Mansfield](https://candidates.democracyclub.org.uk/person/74512/hazel-mansfield)
* [ ] [Marion Donaldson](https://candidates.democracyclub.org.uk/person/19805/marion-donaldson)
* [ ] [Michael Dennis Willis](https://candidates.democracyclub.org.uk/person/74486/michael-dennis-willis)
* [ ] [Neil Mitchison](https://candidates.democracyclub.org.uk/person/71911/neil-mitchison)
* [ ] [Nick Tulloch](https://candidates.democracyclub.org.uk/person/34823/nick-tulloch)
* [ ] [Robbie Gordon Munro](https://candidates.democracyclub.org.uk/person/8509/robbie-gordon-munro)
* [ ] [Sand Owsnett](https://candidates.democracyclub.org.uk/person/73586/sand-owsnett)
* [ ] [Tina McCaffery](https://candidates.democracyclub.org.uk/person/74472/tina-mccaffery)
* [ ] [Tom Wills](https://candidates.democracyclub.org.uk/person/70667/tom-wills)
## [sp.r.lothian.2021-05-06](https://candidates.democracyclub.org.uk/elections/sp.r.lothian.2021-05-06/)
* [ ] [Ashley Graczyk](https://candidates.democracyclub.org.uk/person/20624/ashley-graczyk)
* [ ] [Cara Patricia Wase](https://candidates.democracyclub.org.uk/person/74542/cara-patricia-wase)
* [ ] [Caron Lindsay](https://candidates.democracyclub.org.uk/person/22431/caron-lindsay)
* [ ] [Charles Dundas](https://candidates.democracyclub.org.uk/person/4033/charles-dundas)
* [ ] [Christina Mary Hendry](https://candidates.democracyclub.org.uk/person/74480/christina-mary-hendry)
* [ ] [David Renton](https://candidates.democracyclub.org.uk/person/74319/david-renton)
* [ ] [Emma Watt](https://candidates.democracyclub.org.uk/person/74318/emma-watt)
* [ ] [Gavin Ridley](https://candidates.democracyclub.org.uk/person/74502/gavin-ridley)
* [ ] [Jon Pullman](https://candidates.democracyclub.org.uk/person/74416/jon-pullman)
* [ ] [Kenny MacAskill](https://candidates.democracyclub.org.uk/person/71831/kenny-macaskill)
* [ ] [Lucy Hammond](https://candidates.democracyclub.org.uk/person/74320/lucy-hammond)
* [ ] [Richard Lucas](https://candidates.democracyclub.org.uk/person/7111/richard-lucas)
* [ ] [Sue Webber](https://candidates.democracyclub.org.uk/person/20619/sue-webber)
* [ ] [Vivienne Moir](https://candidates.democracyclub.org.uk/person/74501/vivienne-moir)
## [sp.r.mid-scotland-and-fife.2021-05-06](https://candidates.democracyclub.org.uk/elections/sp.r.mid-scotland-and-fife.2021-05-06/)
* [ ] [Bruce Henderson](https://candidates.democracyclub.org.uk/person/74553/bruce-henderson)
* [ ] [Calum Paul](https://candidates.democracyclub.org.uk/person/21195/calum-paul)
* [ ] [Claire Baker](https://candidates.democracyclub.org.uk/person/9178/claire-baker)
* [ ] [Don Marshall](https://candidates.democracyclub.org.uk/person/74533/don-marshall)
* [ ] [Martin J Keatings](https://candidates.democracyclub.org.uk/person/21131/martin-j-keatings)
* [ ] [Mercy Mugure Kamanja](https://candidates.democracyclub.org.uk/person/74564/mercy-mugure-kamanja)
* [ ] [Stefan Diesing](https://candidates.democracyclub.org.uk/person/74554/stefan-diesing)
## [sp.r.north-east-scotland.2021-05-06](https://candidates.democracyclub.org.uk/elections/sp.r.north-east-scotland.2021-05-06/)
* [ ] [Alison Simpson](https://candidates.democracyclub.org.uk/person/21278/alison-simpson)
* [ ] [Ewan Gurr](https://candidates.democracyclub.org.uk/person/74413/ewan-gurr)
* [ ] [Geoffrey Alexander Farquharson](https://candidates.democracyclub.org.uk/person/74654/geoffrey-alexander-farquharson)
* [ ] [Laura Marshall](https://candidates.democracyclub.org.uk/person/73671/laura-marshall)
## [sp.r.south-scotland.2021-05-06](https://candidates.democracyclub.org.uk/elections/sp.r.south-scotland.2021-05-06/)
* [ ] [Ali Salamati](https://candidates.democracyclub.org.uk/person/22745/ali-salamati)
* [ ] [Michael Banks](https://candidates.democracyclub.org.uk/person/74405/michael-banks)
## [sp.r.west-scotland.2021-05-06](https://candidates.democracyclub.org.uk/elections/sp.r.west-scotland.2021-05-06/)
* [ ] [James Morrison](https://candidates.democracyclub.org.uk/person/74457/james-morrison)
* [ ] [Liam McKechnie](https://candidates.democracyclub.org.uk/person/72497/liam-mckechnie)
* [ ] [Martin Llewellyn Bell](https://candidates.democracyclub.org.uk/person/74693/martin-llewellyn-bell)
* [ ] [Maurice Campbell](https://candidates.democracyclub.org.uk/person/74460/maurice-campbell)

**Comment by symroe** [comment]
This will be fixed since the person forms have been updated, but the above data might still need manually fixing.
