### ISSUE TITLE
add push notifications for notable edits to Slack

### ISSUE THREAD

**Issue by mhl** [DemocracyClub/yournextrepresentative#140]
There are particular types of changes that are worth highlighting for review by experienced volunteers. These might include, for example:

* First edits from any user
* Removal of candidacies

@symroe suggested that we could have push notifications into #candidates on Slack for these types of edits. We can start with the simple criteria above for what makes an event "notable", but add to them over time.

If this is implemented as another RSS feed, like https://candidates.democracyclub.org.uk/feeds/changes.xml we can simply add it to the Slack channel wit these steps: https://get.slack.help/hc/en-us/articles/218688467-Add-RSS-feeds-to-Slack

**Comment by jf1** [comment]
Potential to link with https://github.com/mysociety/yournextrepresentative/issues/980

**Comment by symroe** [comment]
I would like to add the concept of notable people too – someone on Twitter suggested that we lock Jo Cox for example. How we define a notable person is a different issue, but the model for notable edits should consider this I think.

(anyone with a death date is a very good starting point)

**Comment by tfgg** [comment]
- Changes to a person's name where levenshtein_distance(new_name, old_name) > some threshold.

I've previously found this good for finding malicious or incompetent edits. Lots of [candidate name] -> "DELETE THIS", for example :)

**Comment by symroe** [comment]
As a general rule for the time being I'd be happy with a lot of false positives that we can tune out later. It's almost like "filter out insignificant and trusted edits one by one, from a feed of all edits".

**Comment by chris48s** [comment]
There's a number of other notable events that have been discussed that might be useful to be able to detect and include in the feed at some point. I'm going to start collecting them here so we don't forget. Most of these are require more advanced techniques to detect than are currently in use:

* Changes by suspicious/(untrustworthy?) users. For example, if a user who has submitted more than N edits which have been reverted within the last X amount of time submits an edit, that should be automatically flagged for review. (how do we score user 'trustworthiness'?)

* Large bursts of changes in a short period of time from the same user (but obviously filter bulk adding)

* Edit wars: If a field is changed, then changed back and the change is re-done and so on, we want to know about that. Links to the topic of being able to lock a field (so there's an action we can take if we detect an edit war).

**Comment by mhl** [comment]
I'm going to close this, since a basic version is working \o/ and feeding some changes to review to Slack. At the moment it's including:
* The first three edits of any user
* Edits to profiles of people marked as deceased (although we haven't set a date of death for many people whom we know to be deceased)
* Edits to anyone on the "liable to vandalism" list - some party leaders, ministers, etc.

To cover the other features requested on this issue I've created two new issues:

* #230 
* #231
