### ISSUE TITLE
"Elected!" shown twice for one success

### ISSUE THREAD

**Issue by jf1** [DemocracyClub/yournextrepresentative#141]
Minor display bug seen [here](https://candidates.democracyclub.org.uk/person/10418/sean-anstee):
![image](https://cloud.githubusercontent.com/assets/4711363/25434076/d2bfe16e-2a82-11e7-9857-aae58a6b6011.png)
This candidate is involved in a current election as well as having a previous successful candidacy.

Doesn't happen elsewhere [1](https://candidates.democracyclub.org.uk/person/14153/laura-pearsall) [2](https://candidates.democracyclub.org.uk/person/12849/mark-withers). Those candidates have no current election.

**Comment by JoeMitchell** [comment]
Oh I got this on https://candidates.democracyclub.org.uk/person/8802 too 

![image](https://cloud.githubusercontent.com/assets/8096305/25578948/3dc7eb32-2e6b-11e7-8f1d-b03c48017f52.png)

Doesn't matter so long as it's not making it through to Who, I think.
