### ISSUE TITLE
Candidates accidentally being added to first ballot in list

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1419]
There are four candidates standing in the Buckingham ward of Adur council:
https://candidates.democracyclub.org.uk/elections/local.adur.buckingham.2021-05-06/

But all of these candidates are also standing elsewhere - it seems unlikely that any of them is actually a candidate in Adur
![image](https://user-images.githubusercontent.com/10633357/113979051-ad6d1900-983c-11eb-9c1a-5fd37982076e.png)

In each case the candidate themselves appears to have made the edit:
![image](https://user-images.githubusercontent.com/10633357/113978868-641cc980-983c-11eb-9eb6-9db758ac69e8.png)

`local.adur.buckingham.2021-05-06` is the first unlocked ballot in the dropdown - it must be getting selected automatically for a few users?
![image](https://user-images.githubusercontent.com/10633357/113978926-7c8ce400-983c-11eb-9ed9-e8631327d82a.png)

~~I haven't been able to reproduce this issue~~
Oh it's good ol' Internet Explorer - edit a candidate and this it what shows in the New Ballot box:
![image](https://user-images.githubusercontent.com/10633357/113979345-0b016580-983d-11eb-8f26-bc9524c28382.png)

It is not possible to deselect it, so presumably the users are entering their party in the second dropdown just to be able to submit the form

**Comment by michaeljcollinsuk** [comment]
I was able to recreate this issue in safari - I'm opened a pull request #1437 that I think should resolve this. From testing in safari at least, the "New Ballot" field is no longer populated, and it also adds the option to deselect if you select one in error
