### ISSUE TITLE
Create "None specified" party

### ISSUE THREAD

**Issue by jf1** [DemocracyClub/yournextrepresentative#142]
As per this Slack discussion:
![image](https://cloud.githubusercontent.com/assets/4711363/25434863/e99e0a5c-2a85-11e7-8c1a-0f6a2e5948a7.png)

DC's list of parties needs: all those registered [here](http://search.electoralcommission.org.uk/Search/Registrations?currentPage=1&et=pp&et=ppm&register=gb&register=ni&regStatus=registered), **Independent** and a new "**None specified**" party.

Whilst this issue is primarily to deal with the above, it'd also support #122 for an 'expected' candidate who has said they'll stand but hasn't specified a party, eg [here](https://candidates.democracyclub.org.uk/person/34147/aaron-banks).

**Comment by symroe** [comment]
This might be fixed by adding a party description rather than a new party
