### ISSUE TITLE
May 2021 SOPN Parsing issues

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#1426]
Please provide a link to the PDF on the candidates site and a description of what the problem was.

Screen shots can help in some cases, but aren't always needed if the problem is obvious.

**Comment by sjorford** [comment]
https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.stirling.forth-and-endrick.by.2021-05-06/ - only the surname column has been parsed

**Comment by it3986** [comment]
Bot consistently isn't picking up the Party for "Labour and Co-operative Party" candidates in the Westcountry

Examples - https://candidates.democracyclub.org.uk/elections/local.gloucestershire.dursley.2021-05-06/sopn/
https://candidates.democracyclub.org.uk/elections/local.gloucestershire.bisley-and-painswick.2021-05-06/sopn/
https://candidates.democracyclub.org.uk/elections/local.gloucestershire.cam-valley.2021-05-06/sopn/

**Comment by michaeljcollinsuk** [comment]
> Bot consistently isn't picking up the Party for "Labour and Co-operative Party" candidates in the Westcountry.
> Candidate name is showing correctly in the pre-filled data from the bot but the Party field is just blank
> 
> Examples - https://candidates.democracyclub.org.uk/elections/local.gloucestershire.dursley.2021-05-06/sopn/
> https://candidates.democracyclub.org.uk/elections/local.gloucestershire.bisley-and-painswick.2021-05-06/sopn/
> https://candidates.democracyclub.org.uk/elections/local.gloucestershire.cam-valley.2021-05-06/sopn/

What I think happens:
- On the front end, the selections displayed are a mixture of the `Party` object and then related `PartyDescriptions` for each party
- We don't have a `PartyDescription` object with a description of "Labour and Co-operative Party" - only a `Party` object
- This causes the lookup [here](https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/sopn_parsing/helpers/parse_tables.py#L142) to fail so we fall back to [line 148](https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/sopn_parsing/helpers/parse_tables.py#L148)
- This is either returning none (so we don't display it correctly) or we are displaying a description that isn't in the pre-loaded options (e.g. "Labour and Co-operative Party (Joint Description with Labour Party) | Llafur a’r Blaid Gydweithredol") so it doesn't display either - related to #1367

**Comment by JoeMitchell** [comment]
https://candidates.democracyclub.org.uk/elections/local.leicestershire.loughborough-north-west.2021-05-06/sopn/

It's resulting in SURNAMEfirstname

**Comment by JoeMitchell** [comment]
https://candidates.democracyclub.org.uk/elections/mayor.north-tyneside.2021-05-06/sopn/

It's gone completely mad, just making up names?! It's haunted? They're the ghosts of Tyneside past?

**Comment by symroe** [comment]
https://candidates.democracyclub.org.uk/elections/local.fareham.fareham-east.2021-05-06/sopn/

> The SOPN for Fareham Council seems to be off.  It's adding "Name of ward:" and "The following people have been, or stand nominated for election to this ward. Those who no longer stand nominated have a comment in the right-hand column." as candidates, and skipping every second candidate.

**Comment by pmk01** [comment]
Page detection did not work on W. Oxfordshire

**Comment by illicitonion** [comment]
https://candidates.democracyclub.org.uk/elections/local.leeds.burmantofts-richmond-hill.2021-05-06/sopn/ - did not parse out any values, and whatever fetched the PDF messed up the pages such that PETERS, Karen was missing.

**Comment by illicitonion** [comment]
https://candidates.democracyclub.org.uk/elections/local.derbyshire.derwent-valley.2021-05-06/sopn/ - did not parse out any values, nothing looks particularly strange about the PDF

**Comment by illicitonion** [comment]
Another no-parse: https://candidates.democracyclub.org.uk/elections/local.luton.high-town.by.2021-05-06/sopn/

**Comment by illicitonion** [comment]
Nothing from https://candidates.democracyclub.org.uk/elections/local.burnley.lanehead.2021-05-06/sopn/

**Comment by illicitonion** [comment]
Nothing from https://candidates.democracyclub.org.uk/elections/local.sunderland.millfield.2021-05-06/sopn/

**Comment by jf1** [comment]
Trivial but maybe worth fixing - from a blank line on the pdf, an Independent candidate with no name was proposed.
https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.cambridgeshire.sutton.2021-05-06/

**Comment by jf1** [comment]
The blank line issue ^ isn't trivial as I can't get to the next page - clicking `Review` generates an error of `This field is required.` for the non-existent candidate. This is after I've removed the proposed `Independent` party.

**Comment by jf1** [comment]
Though I may have been able to workaround the ^^ above issue by ticking the `Duplicate?` box but it's not present so there's no way to get to the `Review` stage as it errors before then with: `Person 4` `This field is required.` despite there being only 3 people on the SoPN.

**Comment by sjorford** [comment]
Lewisham People Before Profit doesn't show on the bulk add page, even after clicking "Load more parties"
![image](https://user-images.githubusercontent.com/10633357/114185564-c7425500-993d-11eb-9543-783d754b9176.png)
https://candidates.democracyclub.org.uk/elections/local.lewisham.bellingham.by.2021-05-06/sopn/

It does show if you add the candidate directly to the ballot page
![image](https://user-images.githubusercontent.com/10633357/114185648-dd501580-993d-11eb-8fe3-e5bcdb27b5f2.png)

**Comment by jf1** [comment]
https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.liverpool.mossley-hill.2021-05-06/?edit=1 proposed `Green Party` for `The Liberal Party Candidate`

**Comment by symroe** [comment]
Seems like none of Cornwall parsed for some reason: https://candidates.democracyclub.org.uk/elections/local.cornwall.camelford-boscastle.2021-05-06/sopn/

**Comment by illicitonion** [comment]
https://candidates.democracyclub.org.uk/elections/local.devon.yelverton-rural.2021-05-06/sopn/ identified the capital i in Judy Sara Marguerita Maciejowska's surname as an l

**Comment by jf1** [comment]
Page splitting / uploading put the wrong ward into https://candidates.democracyclub.org.uk/elections/local.warrington.stockton-heath.2021-05-06/sopn/

**Comment by jf1** [comment]
The parser didn't get the description `Christchurch Independents` (which is in the `Click to load more...` section) https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.bournemouth-christchurch-and-poole.commons.by.2021-05-06/

**Comment by jf1** [comment]
`Angela S Marynicz` was parsed as `Angela Marynicz S` at https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.devon.seaton-colyton.2021-05-06/

**Comment by jf1** [comment]
This (first Division) wasn't parsed https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.devon.dartmouth-marldon.2021-05-06/
All other Divisions from that pdf were fine https://candidates.democracyclub.org.uk/upload_document/posts_for_document/22039/

**Comment by jf1** [comment]
3 of 5 Divisions were fine in https://candidates.democracyclub.org.uk/upload_document/posts_for_document/21870/
But nothing at https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.devon.ashburton-buckfastleigh.2021-05-06/ and https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.devon.bideford-east.2021-05-06/

**Comment by jf1** [comment]
This one twice gave a 500 when uploading and, unlike all others from the same LA, it wasn't parsed https://candidates.democracyclub.org.uk/elections/local.gloucestershire.highnam.2021-05-06/sopn/

**Comment by jf1** [comment]
From RyanC... Another example of bad parsing https://candidates.democracyclub.org.uk/elections/local.leicestershire.loughborough-east.2021-05-06/sopn/
![image](https://user-images.githubusercontent.com/4711363/114312006-0234bc00-9ae9-11eb-921f-3cb846cb8ba3.png)

**Comment by jf1** [comment]
SUCCESS from a HTML->PDF converted SoPN https://candidates.democracyclub.org.uk/elections/local.south-hams.ivybridge-west.by.2021-05-06/sopn/

**Comment by jf1** [comment]
Didn't get any forenames from https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.welwyn-hatfield.brookmans-park-little-heath.2021-05-06/

**Comment by jf1** [comment]
Via BoP: https://candidates.democracyclub.org.uk/elections/local.suffolk.thedwastre-north.2021-05-06/sopn/ parsed Harry Richardson as Richardson Harry

**Comment by VirginiaDooley** [comment]
> 

This bug has been fixed with https://github.com/DemocracyClub/yournextrepresentative/pull/1711

**Comment by VirginiaDooley** [comment]
> Bot consistently isn't picking up the Party for "Labour and Co-operative Party" candidates in the Westcountry. Candidate name is showing correctly in the pre-filled data from the bot but the Party field is just blank
> 
> Examples - https://candidates.democracyclub.org.uk/elections/local.gloucestershire.dursley.2021-05-06/sopn/ https://candidates.democracyclub.org.uk/elections/local.gloucestershire.bisley-and-painswick.2021-05-06/sopn/ https://candidates.democracyclub.org.uk/elections/local.gloucestershire.cam-valley.2021-05-06/sopn/

This bug has been fixed with https://github.com/DemocracyClub/yournextrepresentative/pull/1711

**Comment by VirginiaDooley** [comment]
> https://candidates.democracyclub.org.uk/elections/local.fareham.fareham-east.2021-05-06/sopn/
> 
> > The SOPN for Fareham Council seems to be off.  It's adding "Name of ward:" and "The following people have been, or stand nominated for election to this ward. Those who no longer stand nominated have a comment in the right-hand column." as candidates, and skipping every second candidate.

There may be some issue with the version of this PDF. It uploads blank when I test it.

**Comment by VirginiaDooley** [comment]
> 

@pmk01 Do you have a ballot id I can test?

**Comment by VirginiaDooley** [comment]
> Page detection did not work on W. Oxfordshire

@pmk01 Do you have a ballot id I can test?

**Comment by pmk01** [comment]
I honestly don't remember this! It's possible this was raised by a volunteer in the Slack and I added it here. I presume this is the issue: https://candidates.democracyclub.org.uk/elections/local.west-oxfordshire.witney-east.2021-05-06/sopn/

**Comment by VirginiaDooley** [comment]
> https://candidates.democracyclub.org.uk/elections/local.leeds.burmantofts-richmond-hill.2021-05-06/sopn/ - did not parse out any values, and whatever fetched the PDF messed up the pages such that PETERS, Karen was missing.

@illicitonion This SOPN was either incorrectly published by the council or possibly printed to PDF from an html file (or both).

**Comment by VirginiaDooley** [comment]
> 



> https://candidates.democracyclub.org.uk/elections/local.derbyshire.derwent-valley.2021-05-06/sopn/ - did not parse out any values, nothing looks particularly strange about the PDF

@illicitonion This was solved with https://github.com/DemocracyClub/yournextrepresentative/pull/1697

**Comment by VirginiaDooley** [comment]
> Another no-parse: https://candidates.democracyclub.org.uk/elections/local.luton.high-town.by.2021-05-06/sopn/ and https://candidates.democracyclub.org.uk/elections/local.luton.round-green.by.2021-05-06/sopn/

@illicitonion Table parsing error; Header cannot be found; moving to https://github.com/DemocracyClub/yournextrepresentative/issues/1728

**Comment by VirginiaDooley** [comment]
> elections/local.burnley.lanehead.2021-05-06/sopn/



> Nothing from https://candidates.democracyclub.org.uk/elections/local.burnley.lanehead.2021-05-06/sopn/

@illicitonion Ward matching error (table parsing error); moving to #1728

**Comment by VirginiaDooley** [comment]
> Nothing from https://candidates.democracyclub.org.uk/elections/local.sunderland.millfield.2021-05-06/sopn/

@illicitonion Fixed with https://github.com/DemocracyClub/yournextrepresentative/pull/1711

**Comment by VirginiaDooley** [comment]
> Trivial but maybe worth fixing - from a blank line on the pdf, an Independent candidate with no name was proposed. https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.cambridgeshire.sutton.2021-05-06/

@jf1 Table parsing error; moving to #1728

**Comment by VirginiaDooley** [comment]
> elections/local.lewisham.bellingham.by.2021-05-06/sopn/



> Lewisham People Before Profit doesn't show on the bulk add page, even after clicking "Load more parties" ![image](https://user-images.githubusercontent.com/10633357/114185564-c7425500-993d-11eb-9543-783d754b9176.png) https://candidates.democracyclub.org.uk/elections/local.lewisham.bellingham.by.2021-05-06/sopn/
> 
> It does show if you add the candidate directly to the ballot page ![image](https://user-images.githubusercontent.com/10633357/114185648-dd501580-993d-11eb-8fe3-e5bcdb27b5f2.png)

Fixed with https://github.com/DemocracyClub/yournextrepresentative/pull/1712; Further improvements in https://github.com/DemocracyClub/yournextrepresentative/pull/1730

**Comment by VirginiaDooley** [comment]
> https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.liverpool.mossley-hill.2021-05-06/?edit=1 proposed `Green Party` for `The Liberal Party Candidate` Then when I reloaded that page all of the proposed parties were `Green Party`.

Fixed with https://github.com/DemocracyClub/yournextrepresentative/pull/1711

**Comment by VirginiaDooley** [comment]
> https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.liverpool.mossley-hill.2021-05-06/?edit=1 proposed `Green Party` for `The Liberal Party Candidate` Then when I reloaded that page all of the proposed parties were `Green Party`.

> Seems like none of Cornwall parsed for some reason: https://candidates.democracyclub.org.uk/elections/local.cornwall.camelford-boscastle.2021-05-06/sopn/

@symroe Table parsing error: No `ParsedSOPN`; moving to #1728

**Comment by VirginiaDooley** [comment]
> The parser didn't get the description `Christchurch Independents` (which is in the `Click to load more...` section) https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.bournemouth-christchurch-and-poole.commons.by.2021-05-06/

@jf1 Fixed with #1712; Further improvements in #1730

**Comment by VirginiaDooley** [comment]
@jf1 
Angela S Marynicz` was parsed as `Angela Marynicz S` at https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.devon.seaton-colyton.2021-05-06/ 

**Table parsing error; moving to #1728**

Also the Green candidate at https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.devon.exmouth.2021-05-06/ 

**Fixed with #1712**

And 4 with a middle initial at https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.devon.exmouth-budleigh-salterton-coastal.2021-05-06/ 

**Table parsing error; moving to #1728**

1 more at https://candidates.democracyclub.org.uk/elections/local.devon.feniton-honiton.2021-05-06/sopn/ 

**Table parsing error; moving to #1728**

1 person with 2 initials at https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.devon.sidmouth.2021-05-06/ 

**Table parsing error; moving to #1728**

Then nothing at all parsed for the first or last Divisions in the same pdf https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.devon.broadclyst.2021-05-06/ https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.devon.whimple-blackdown.2021-05-06/

**Fixed with #1712; Further improvements in #1730 but still has initial placing issue in table parsing so will move to #1728**
> 
> 3 more people with initials misplaced, in a different pdf from the same authority https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.devon.axminster.2021-05-06/

**Table parsing error; moving to #1728**

**Comment by VirginiaDooley** [comment]
> I honestly don't remember this! It's possible this was raised by a volunteer in the Slack and I added it here. I presume this is the issue: https://candidates.democracyclub.org.uk/elections/local.west-oxfordshire.witney-east.2021-05-06/sopn/

@pmk01 Page matching error; moving to https://github.com/DemocracyClub/yournextrepresentative/issues/1726

**Comment by VirginiaDooley** [comment]
> From RyanC... Another example of bad parsing https://candidates.democracyclub.org.uk/elections/local.leicestershire.loughborough-east.2021-05-06/sopn/ ![image](https://user-images.githubusercontent.com/4711363/114312006-0234bc00-9ae9-11eb-921f-3cb846cb8ba3.png)

Name parsing error in table parsing; moving to https://github.com/DemocracyClub/yournextrepresentative/issues/1728 for further inspection

**Comment by VirginiaDooley** [comment]
> Didn't get any forenames from https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.welwyn-hatfield.brookmans-park-little-heath.2021-05-06/ Same here (via JoeCL) https://candidates.democracyclub.org.uk/elections/local.welwyn-hatfield.sherrards.2021-05-06/sopn/ And (via BoP) https://candidates.democracyclub.org.uk/elections/local.welwyn-hatfield.haldens.2021-05-06/sopn/

Table extraction error; moving to https://github.com/DemocracyClub/yournextrepresentative/issues/1727

**Comment by VirginiaDooley** [comment]
> Via BoP: https://candidates.democracyclub.org.uk/elections/local.suffolk.thedwastre-north.2021-05-06/sopn/ parsed Harry Richardson as Richardson Harry

Table parsing error; moving to #1728

**Comment by VirginiaDooley** [comment]
> Trivial but maybe worth fixing - from a blank line on the pdf, an Independent candidate with no name was proposed. https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.cambridgeshire.sutton.2021-05-06/

Fixed with https://github.com/DemocracyClub/yournextrepresentative/pull/1731#pullrequestreview-868265758

**Comment by symroe** [comment]
Closing this as we've either fixed the issues or we're tracking new issues in #1727
