### ISSUE TITLE
Add photo policy text to upload and/or about pages

### ISSUE THREAD

**Issue by jf1** [DemocracyClub/yournextrepresentative#144]
When [moderating a photo](https://candidates.democracyclub.org.uk/moderation/photo/review/6603) the policy is displayed as:
Photo policy
The photo must be a clear, recent, colour headshot of the candidate.
No text or party logos may be included in the photo, unless an unavoidable part of the background or a small rosette/badge that doesn’t interfere with the rule above. Any photo containing party text or logos should be replaced by a plain photo whenever one is available.

However this text is not shown when [uploading a photo](https://candidates.democracyclub.org.uk/moderation/photo/upload/2512).

It'd also be useful on the about page, above or below Privacy Policy and ideally with an anchor eg https://candidates.democracyclub.org.uk/help/about#PhotoPolicy so a link can be included in rejection messages.

**Comment by octopusinvitro** [comment]
Addressed in https://github.com/DemocracyClub/yournextrepresentative/pull/189
