### ISSUE TITLE
Name from SOPN bulk-add should be added to "alternative names"

### ISSUE THREAD

**Issue by russss** [DemocracyClub/yournextrepresentative#1443]
Adding an existing candidate to a ballot through the bulk-add process causes their name from the SOPN to be ignored. I think it should at least be added to that candidate's alternative names.

This year I feel like we're seeing an increasing number of surname changes for people who are already in the database. The way it currently works, the new surname isn't recorded at all, and the candidate will be listed under their previous/maiden name (unless someone manually goes in and edits the candidate).

Ideally it would be nice to ask the person importing whether they would like that candidate's primary name to be changed, but I think this would be annoyingly noisy due to the middle names.

This seems similar but not identical to #881.

**Comment by jf1** [comment]
This issue also affects a candidates Party Description - if they match an existing candidate we can't set a description.

I think there's also an inconsistency whereby one method adds a new name as an alternative (or the main then shifting the original) but the other method of adding candidates can lead to their original and new names both being recorded - I'd need to redo it to get a more specific description but hopefully you'll be able to see what I mean.

**Comment by jf1** [comment]
I've just confirmed that if you match someone at the /review stage then it does add the alternative name, as can be seen with this candidate https://candidates.democracyclub.org.uk/person/14840/stephen-boulton
