### ISSUE TITLE
May 2021 election (created with typo) needs to be cancelled

### ISSUE THREAD

**Issue by jf1** [DemocracyClub/yournextrepresentative#1446]
The correct one (Pinho**e**) is all ok.
The one to be cancelled is https://candidates.democracyclub.org.uk/elections/local.devon.pinhow-mincinglake.2021-05-06/

**Comment by jf1** [comment]
Another one, we need to keep https://candidates.democracyclub.org.uk/elections/local.leicestershire.castle-donington-kegworth.2021-05-06/ and delete https://candidates.democracyclub.org.uk/elections/local.leicestershire.castle-donnington-kegworth.2021-05-06/

**Comment by jf1** [comment]
Sklemersdale East is still hanging around https://candidates.democracyclub.org.uk/elections/local.lancashire.sklemersdale-east.2021-05-06/

**Comment by sjorford** [comment]
These have all been deleted now
