### ISSUE TITLE
Allow upload of WebP images

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1463]
e.g. uploading https://static.wixstatic.com/media/8baa51_24b3f92ac5ff4bd9a33f2443fa400e03~mv2.jpg/v1/crop/x_165,y_209,w_941,h_1080/fill/w_345,h_396,al_c,q_80,usm_0.66_1.00_0.01/image0_edited.webp
to https://candidates.democracyclub.org.uk/moderation/photo/upload/image/77192

![image](https://user-images.githubusercontent.com/10633357/115532073-5aa84e00-a28d-11eb-8649-8824243a5ab9.png)

Uploading by URL returns a plain 404 page with the text
The image at https://static.wixstatic.com/media/8baa51_24b3f92ac5ff4bd9a33f2443fa400e03~mv2.jpg/v1/crop/x_165,y_209,w_941,h_1080/fill/w_345,h_396,al_c,q_80,usm_0.66_1.00_0.01/image0_edited.webp wasn't of a known type

**Comment by VirginiaDooley** [comment]
WebP images are now accepted via the candidate url photo upload form.
