### ISSUE TITLE
[policy] How to deal with candidates deleting their contact data?

### ISSUE THREAD

**Issue by torotil** [DemocracyClub/yournextrepresentative#1472]
### Issue and Steps to Reproduce

How should we deal with candidates deleting their contact details?

### Screenshots

![Screenshot_20210427_142243](https://user-images.githubusercontent.com/182122/116240470-28529100-a764-11eb-913e-f951fbf529b6.png)

#### Expected

Have a clear guideline of whether to revert such edits or keep them.

#### Actual

No idea how this should be handled and what the legal situation is.

**Comment by jf1** [comment]
For reference: https://candidates.democracyclub.org.uk/person/4710/robin-hunter-clarke

Generally if a candidate asks for removal of anything other than their name, party and candidacy then we oblige.

I was going to state that we don't even know if the links are still valid, and it seems Peter has confirmed they're not and removed them.

**Comment by torotil** [comment]
Ok, good to know. Thanks!
