### ISSUE TITLE
Improve first link on /uk_results page - direct potential wombles to the new filtered system

### ISSUE THREAD

**Issue by jf1** [DemocracyClub/yournextrepresentative#1494]
The first link on https://candidates.democracyclub.org.uk/uk_results/ is to https://candidates.democracyclub.org.uk/uk_results/no-results/ and there's now opportunity to change this to the more useful https://candidates.democracyclub.org.uk/elections/?has_results=0&is_cancelled=0 which allows users to then select a filter or enter a postcode to find wombling tasks of (more) interest.

**Comment by VirginiaDooley** [comment]
Closed with https://github.com/DemocracyClub/yournextrepresentative/pull/1883
