### ISSUE TITLE
Photo upload efficiency improvements

### ISSUE THREAD

**Issue by jf1** [DemocracyClub/yournextrepresentative#150]
## Part 1
Current flow:
1. Go to candidate page
2. Click: `Edit candidate`
3. Wait for superfluous edit candidate page to load
4. Click: `There’s a separate page for uploading a photo`

Instead, at 2, under the `Edit candidate` button, a link for `Or upload a photo` (of [candidate name]) could be placed here to replace steps 2 and 3 with a single click achieving what step 4 currently does.

## Part 2
On the [photo upload page](https://candidates.democracyclub.org.uk/moderation/photo/upload/2512) the uploader isn't shown the photo policy (see #144).

## Part 3
It'd also be useful to tell uploaders that the final result will be a square image, so they should be discouraged from cropping it manually or ideally they would be given the same cropping text and function that's on the [photo moderation page](https://candidates.democracyclub.org.uk/moderation/photo/review/5657).

## Part 4
As mentioned in https://github.com/mysociety/yournextrepresentative/issues/981 the best option for uploaders would be if, as well as the option to upload a file, they had another option to:
Enter two URLs ([image url](https://pbs.twimg.com/media/C9Rt32wXgAAEEVY.jpg:large) and [source url](https://twitter.com/UUPWestTyrone/status/852427059804745728))
Then crop the photo themselves before clicking `Submit`.

Photos can be automatically imported from facebook using:
https://developers.facebook.com/docs/graph-api/reference/user/picture/
https://developers.facebook.com/docs/graph-api/reference/page/picture/

---

Updated by @octopusinvitro to split the issue in its different parts

**Comment by mhl** [comment]
There are a lot of different suggestions here, but I've suggested that @octopusinvitro does this bit today first of all:

> Instead, at 2, under the Edit candidate button, a link for Or upload a photo (of [candidate name]) could be placed here to replace steps 2 and 3 with a single click achieving what step 4 currently does.

And after that we'll look at adding the policy text, and after that upload from a URL.

**Comment by JoeMitchell** [comment]
Remember that Joe R in his facebook video was trying to click on the blank face image below!  

![image](https://cloud.githubusercontent.com/assets/8096305/25807550/1de0e99c-33ff-11e7-89fa-2d7bfe266141.png)

**Comment by JoeMitchell** [comment]
(Sorry if this is too late!)

**Comment by mhl** [comment]
@JoeMitchell yep - thanks, @zarino and @octopusinvitro have watched the video and noted that.

**Comment by octopusinvitro** [comment]
I have edited the issue to split all the different parts.

Part I done here: #176 

I'm gonna start now working on part 2 if nobody is working on it
