### ISSUE TITLE
Error 500 adding Wikidata to a candidate

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1508]
### Issue and Steps to Reproduce

Edited https://candidates.democracyclub.org.uk/person/82127/update and added [Wikidata ID](https://www.wikidata.org/wiki/Q98792749) - the server returned a `500` error after submitting

### Screenshots
![image](https://user-images.githubusercontent.com/10633357/117984516-d139e800-b32f-11eb-837f-61214ad470bf.png)

### Additional Details
* Firefox 88.0.1 on Win10

**Comment by michaeljcollinsuk** [comment]
Closed by #1509
