### ISSUE TITLE
Missing party names in CSV

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1521]
There are a few rows in the CSV that have no value in the `party_name` column:

| id | name | ballot_paper_id | party_id | party_name | correct_party_name |
|-|-|-|-|-|-|
| 45680 | Candice Atterton | gla.c.south-west.2020-05-07 | joint-party:53-119 |  | Labour and Co-operative Party |
| 45875 | Arran Paul Angus | local.waltham-forest.grove-green.by.2021-06-10 | party:90 |  | Liberal Democrats |
| 75673 | Adrian St John Holmes | local.norfolk.sewell.2021-06-17 | party:63 |  | Green Party |
| 51416 | Douglas Wade | local.kent.elham-valley.2021-06-17 | party:63 |  | Green Party |
| 61232 | Gary Champion | local.norwich.sewell.2021-06-17 | party:63 |  | Green Party |
| 61230 | Helen Arundell | local.norwich.sewell.2021-06-17 | party:90 |  | Liberal Democrats |
| 61230 | Helen Arundell | local.norfolk.sewell.2021-06-17 | party:90 |  | Liberal Democrats |
| 32663 | Julie Dawn Brociek-Coulton | local.norfolk.sewell.2021-06-17 | party:53 |  | Labour Party |
| 61235 | Laura Elizabeth McCartney-Gray | local.norwich.sewell.2021-06-17 | party:53 |  | Labour Party |
| 29702 | Susan Carey | local.kent.elham-valley.2021-06-17 | party:52 |  | Conservative and Unionist Party |

see also #1520 which may be related

**Comment by symroe** [comment]
There is one route for adding/updating people that isn't setting `Membership.party_name` (etc). 

The tasks here are:

1. Identify the route that's not performing the update
2. Fix and test
3. Correct the data in the database - this might best be done by writing a management command that does the update, so we can run it again should we need to.

The same applies to party descriptions on memberships I expect, but that's untested.

**Comment by michaeljcollinsuk** [comment]
Will be fixed by https://github.com/DemocracyClub/yournextrepresentative/pull/1673
