### ISSUE TITLE
Prevent changing name on locked and current ballots

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/yournextrepresentative#1545]
Changing the name is a very common thing for vandals to do. Candidate name changes (from new users?) should need review before they are applied. This is to secure against vandalism, especially as this information is pulled across to the Electoral Commission site. 

## Implementation idea

We already have an `OtherName` model for storing other names against people.

This model can be used as a sort of review queue if we add a new `review_status` field.

With a new "edit_name" method on the `Person` model, we can implement the following logic:

```mermaid
flowchart TD

set_person_name[Set Person.name]

edit[Make an edit]
create_other_name[Create OtherName]
mark_other_name_need_review[Mark the OtherName as needing review]
person_has_locked_ballot[Person has locked & current ballots]

edit -->|New person| set_person_name
edit -->|Existing person| create_other_name



create_other_name --> person_has_locked_ballot

person_has_locked_ballot -->|User can lock| set_person_name
person_has_locked_ballot -->|Untrusted user| mark_other_name_need_review --> hide_name[Hide OtherName]
create_other_name -->|No current locked ballots| set_person_name

mark_other_name_need_review --> review_name[Trusted user reviews]
review_name --> |Name ok| set_person_name
review_name --> |Name bad| delete_other_name[Delete Other Name]
delete_other_name --> flag[Flag? Post to Slack?]

```

This looks complex, but the basic idea is:

1. If this is a new person, set `Person.name` and be done with it (no `OtherName` needed)
2. If this is an existing person:
    1. Create an `OtherName` model
    2. Figure out if the person has a current and locked ballot
    3. If so (and the editing user isn't trusted), mark that name as needing review
    4. Once the name is reviewed, set it as the primary name (this can be done by calling `Person.edit_name` again, as the user will be trusted this time

The call to `edit_name` should apply to all places where a user can edit a person. This includes (at least), the SOPN bulk adding forms and the lock review pages.

We also need a new permission "Trusted to change name on locked and current ballots". People with this permission will be able to see a queue of names that need review, in the same way as they can the lock review or photo review screens.

**Comment by pmk01** [comment]
Note: this should only apply to candidates on ballots which are current & locked

**Comment by VirginiaDooley** [comment]
The work here is to prevent the change on ballots that are current & locked AND to add the ability for the user to request a name change.

**Comment by VirginiaDooley** [comment]
@symroe The diagram is very helpful, thanks! I'm wondering with this moderation system if the case is always so clear (good vs evil)? @pmk01 If not, I wonder if a third, not sure > post to slack to crowdsource an opinion might be useful? I suppose there may be untrusted users in Slack 🤔

**Comment by pmk01** [comment]
@VirginiaDooley good point. I think that could be really useful, but I wonder if linking the site to Slack like that is sensible in the long-run?

Some security could be added by providing a field for the user to add a link or whatever to justify their edit (this is also needed for duplicate suggestions!).

(I didn't know you could edit other people's posts! Maybe GH needs an edit review process! 😆)
