### ISSUE TITLE
Search by surname-only sometimes doesn't work

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#155]
I don't think there's an existing issue for this — I did have a little nose around, promise. But do close this one if I'm wrong.

I was wanting to see if we already had Anneliese Dodds in the system, so I searched for 'Dodds': 

![image](https://cloud.githubusercontent.com/assets/8096305/25578999/ba3ca888-2e6b-11e7-911e-0f74fab9f8b5.png)

Searching for 'Anneliese': 

![image](https://cloud.githubusercontent.com/assets/8096305/25579002/d40f1fb6-2e6b-11e7-95c5-677d0f71b6b5.png)

Spooky! Should have appeared in the first search, shurely?

**Comment by symroe** [comment]
The candidate search is limit to 5 results, and all 5 in the top search have 'Dodds' in them. It's just that it didn't weight your result in the top 5 – but how would it know to?

**Comment by JoeMitchell** [comment]
Ah, okay. Is it limited to make it less messy when adding-from-nomination-papers? 

I would not have guessed that the search was limited to five. We could add a `We only display five search results.` notice. But then people would be all like "why only five?!!?!"

**Comment by jf1** [comment]
I was planning on starting a similar issue - do you want to rename this one to reflect the 5-result limit?
eg. 5 result limit prevents people being found using search

Can you do something like: If the fifth result exactly (or highly enough) satisfies the search then show the sixth result and check the next result, repeating until they become vague matches.

I've seen several examples, the hardest to workaround being [Jo Cox](https://candidates.democracyclub.org.uk/person/4262/jo-cox) who's [impossible](https://candidates.democracyclub.org.uk/search?q=%22Jo+Cox%22) to [find using the search](https://candidates.democracyclub.org.uk/search?q=jo+cox).

**Comment by pmk01** [comment]
We now show 10!

**Comment by pmk01** [comment]
I'm going to close this as I think it's superseded by https://github.com/DemocracyClub/yournextrepresentative/issues/1107

(the basic issue is the same, though, just with 10 instead of 5)
