### ISSUE TITLE
Redesign photo uploader process

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#1607]
This issue is a parent issue for everything in the search:

https://github.com/DemocracyClub/yournextrepresentative/issues?q=is%3Aissue+is%3Aopen+label%3A%22Photo+Uploader%22

We should think about the process from scratch, as tweaking the existing process might not end up with the best design.

**Comment by VirginiaDooley** [comment]
Closed with https://github.com/DemocracyClub/yournextrepresentative/pull/1776
