### ISSUE TITLE
Add a field for 'Favourite biscuit' 🍪

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#173]
Inspired by the [Mumsnet biscuit question](http://www.telegraph.co.uk/news/2016/08/23/how-every-politician-has-answered-mumsnets-favourite-biscuit-que/) I think it would be newsworthy, fun, shareable, humanising etc — to add this field to the database. Probably just in the UK, hence on this repo not mySociety's.

Nom nom nom.

**Comment by symroe** [comment]
"A Strong and stable Macaron"

**Comment by mhl** [comment]
Linking this to: https://github.com/DemocracyClub/yournextrepresentative/pull/188

**Comment by hugovk** [comment]
https://github.com/DemocracyClub/yournextrepresentative/pull/188 is merged; this can be closed.

**Comment by JoeMitchell** [comment]
It gives me great pleasure to announce this biscuit issue, closed! 

https://media2.giphy.com/media/on967NSrcVQQ0/giphy.gif
