### ISSUE TITLE
Bulk adding by party throws 500 error

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1733]
e.g.
[2022 Croydon local election](https://candidates.democracyclub.org.uk/elections/local.croydon.2022-05-05/) 
=> [Add candidates for a single party](https://candidates.democracyclub.org.uk/bulk_adding/party/local.croydon.2022-05-05/) 
=> [Conservative and Unionist Party](https://candidates.democracyclub.org.uk/bulk_adding/party/local.croydon.2022-05-05/PP52/) 
=> Server Error (500)

**Comment by VirginiaDooley** [comment]
When I run this locally: 
`
Template error:
In template /Users/virginiadooley/Documents/development/yournextrepresentative/ynr/templates/base.html, error at line 0
   unsupported operand type(s) for +: 'int' and 'NoneType'

Exception Type: TypeError at /bulk_adding/party/local.croydon.2022-05-05/PP52/
Exception Value: unsupported operand type(s) for +: 'int' and 'NoneType'
`

**Comment by michaeljcollinsuk** [comment]
> e.g.
> [2022 Croydon local election](https://candidates.democracyclub.org.uk/elections/local.croydon.2022-05-05/)
> => [Add candidates for a single party](https://candidates.democracyclub.org.uk/bulk_adding/party/local.croydon.2022-05-05/)
> => [Conservative and Unionist Party](https://candidates.democracyclub.org.uk/bulk_adding/party/local.croydon.2022-05-05/PP52/)
> => Server Error (500)

This is now fixed and deployed
