### ISSUE TITLE
Update SOPN parser to extract previous affiliation if it exists

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#1766]
Refs https://github.com/DemocracyClub/yournextrepresentative/issues/1765

From May 2022 Wales SOPNs will have a new column that will list any present previous party affiliation in the last year. 

The Parsing code will have to deal with this case, and where possible extract the party in to the `RawPeople`object for later adding to a `Membership` object.

We have a sample SOPN, so we need to write some tests for the sample, update the parser and ensure that we capture the data.

For the moment we can assume that the previous party will be an exact match to the EC's party register (e.g, the same sort of object as the "description" column is on the SOPNs). This means we should be able to use the same party matching logic as we currently have. It's unlikely that a party description will be added, as this is about party memberships rather than previous candidacies.

**Comment by michaeljcollinsuk** [comment]
Closed by #1805
