### ISSUE TITLE
Add helpers for Welsh only features

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#1767]
We're about to add a load of features that only apply in Wales. 

It's easy to imagine that we'll add other country specific features in future.

We should add a helper on `Ballot` to let us know if it's in Wales or not. Chances are this can be taken form the NUTS1 value from EE.

**Comment by symroe** [comment]
This is actually for Welsh government run elections (`senedd.` and `local.` in Wales)

**Comment by michaeljcollinsuk** [comment]
Closed by https://github.com/DemocracyClub/yournextrepresentative/commit/5e422d4d72e1811f0499b7c9aebab801e04fd7b8
