### ISSUE TITLE
Modify bulk adding and person edit forms to include SOPN-based party affiliation

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#1768]
As part of #1765 we will need a way to edit the previous party affiliation in the frontend interface.

There are some considerations to this:

Previous affiliation _is not_ the same as previous candidacies in our system. We don't want users trying to populate old elections data on this field. It's _only_ for storing information that's presented on Welsh SOPNs.

Because of this, we should limit how and when the information can be edited. Firstly, it should only be shown for Welsh ballots (see #1767). Next, we should only show the field when the ballot has a SOPN attached, not before. This is because it will be impossible to enter any information to the field before the SOPN is published. 

In terms of the interface: Adding to the person edit form isn't so hard. We add another party select drop down, excluding party descriptions, and filtering on parties that were active in the 12 months before the election date.

The bulk adding form might be more complex, and we don't want to add another drop down to every row of Welsh ballots. We might want to add the input in the HTML but hide it with JS and add a button to add the data inline (showing the input when clicked). This needs some design work.

We also need to show the data on the bulk add review screen, so people locking ballots can verify the data.

**Comment by michaeljcollinsuk** [comment]
> In terms of the interface: Adding to the person edit form isn't so hard. We add another party select drop down, excluding party descriptions, and filtering on parties that were active in the 12 months before the election date.

@symroe on the person edit form (e.g. https://candidates.democracyclub.org.uk/person/25034/update) we dont currently allow users to edit previous candidacies, only add new ones. So do we want to allow the previous party affiliation from here? If so, do you think we list the candidacies and then display the new field to change the party affiliation?

**Comment by michaeljcollinsuk** [comment]
Ah actually I see when the ballot is unlocked, you can edit a candidacy from the person edit form e.g. https://candidates.democracyclub.org.uk/person/84503/update

So to edit the `previous_party_affiliation` person edit page, it would only be possible during the small window of SOPN being uploaded, but the ballot not locked, is that right?

**Comment by michaeljcollinsuk** [comment]
Re: bulk add form. How should we handle candidates that have already been added to a ballot pre-SOPN being uploaded, that are standing, but now need editing to add the additional party?

Example screenshot of my WIP:
![Screenshot 2022-03-15 at 15 34 52](https://user-images.githubusercontent.com/15347726/158414162-e9df3cdd-827b-4cd6-9a66-a836e1d4d349.png)

I was thinking we could add a new button to the "Actions" column to display a form to add the previous parties and then submit over ajax? This may be what was already planned, but wanted to confirm before taking further

**Comment by michaeljcollinsuk** [comment]
Closed by https://github.com/DemocracyClub/yournextrepresentative/pull/1798
