### ISSUE TITLE
Add previous party affiliation to Membership model

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#1769]
As part of #1769.

We need to store the previous party affiliation on the `Membership` model. For the time being we can assume that this can be a FK to the `Party` model, as we assume that the values on the SOPN will be to valid UK political parties.

**NOTE**: we should model previous parties as a list, not a single party. This is because the nomination forms ask for previous partieS, and it's possible someone has been a member of more than one in the last year (THAT would be an interesting story!)

- [x] Add some validation that the value is only stored for Welsh ballots
- [x] Ensure merging and reverts work
- [x] Update test fixtures for Welsh Memberships

**Comment by michaeljcollinsuk** [comment]
Closed by https://github.com/DemocracyClub/yournextrepresentative/issues/1769
