### ISSUE TITLE
clearer example names 

### ISSUE THREAD

**Issue by samsmith** [DemocracyClub/yournextrepresentative#1848]
### Issue and Steps to Reproduce
various form say: "Person Name (style: Ali Smith, not SMITH Ali)"

Add a middle name to the example so people know to enter those too:

"Person Name (style: Ali Beth Smith, not SMITH Ali Beth)"
#### Expected

submitters should type full names from the SOPNS (and elsewhere)

#### Actual

submitters only type first and surnames from SOPNs

### Additional Details
* Browser and version
* Were you logged in?

**Comment by jf1** [comment]
Are we sure that middle names are retained if they're typed or parsed but then at the next stage there's a match with an existing candidate without the middle name?

**Comment by sjorford** [comment]
If you match against an existing candidate it ignores the name that was scraped/typed from the SOPN - this is issue #1443

**Comment by samsmith** [comment]
this issue was purely about the help text displayed on the page as examples, not any form of matching or parsing (there are many other issues about those)
