### ISSUE TITLE
Search doesn't find people with certain short names

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1860]
e.g. search for "[Tony Over](https://candidates.democracyclub.org.uk/search?q=Tony+Over)" doesn't find [Tony Over](https://candidates.democracyclub.org.uk/person/56233/tony-over)

![image](https://user-images.githubusercontent.com/10633357/163429870-be52ea3c-7de2-4fb3-84f6-bd2112d39e94.png)

Similarly "[Ann Were](https://candidates.democracyclub.org.uk/search?q=Ann+Were)" doesn't find [Ann Were](https://candidates.democracyclub.org.uk/person/87214)

I assume it is the surnames which look like short English words - searching for "Ann" finds lots of people, searching for "Were" finds none. A search for "[Jeff Love](https://candidates.democracyclub.org.uk/search?q=Jeff+Love)" works fine as well

Edie: Add "[Will](https://candidates.democracyclub.org.uk/search?q=Will)" to the list of blocked names

**Comment by jf1** [comment]
Great spot @sjorford!

**Comment by jf1** [comment]
Looks like @sym's recent changes have fixed this :)
