### ISSUE TITLE
Indicate that we think a bot can import results for an area

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#1881]
When we think a bot will import data for an area (based on https://github.com/DemocracyClub/yournextrepresentative/pull/1880/commits/da45396f069768c5bdbb59d66ff1bddb3bcca152) then we should find a way of telling users to focus elsewhere, to save them doing something a bot can do. 

This doesn't have to be a very neat solution: a list of election IDs in settings that we can pull through to a template would do the job.

**Comment by VirginiaDooley** [comment]
@symroe Did you want the user to be notified on the election results page `/uk_results/no-results/` or a message next to an election on the list of elections `/uk_results/local.city-of-london.aldersgate.2022-03-24/`?

**Comment by VirginiaDooley** [comment]
[This conditional ](https://github.com/DemocracyClub/yournextrepresentative/blob/1831c08aaf45a45634d274cff8554d94ad4a00e2/ynr/apps/uk_results/templates/uk_results/ballot_paper_results_form.html#L15) along with the `store_modgov_urls`  mgmt command (run manually on the server after the latest URLs are deployed) addresses this issue. [This work](https://github.com/DemocracyClub/yournextrepresentative/pull/1883/commits/6a2fc94dc10e1b6e8ed1199679b1c6402e144e58) would stop the results entry from being accessed until after the polls close.
