### ISSUE TITLE
Add Mastodon to list of social media accounts

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#1931]
From @sjorford:

> starting to see the occasional candidate with a Mastodon account - worth adding to the list of links maybe?

* [x] Add to person edit form
* [x] Output in CSVs
* [ ] Explore pulling in photos like we do with TwitterBot?

**Comment by sjorford** [comment]
you might also want to consider what happens when someone moves servers, e.g. https://mastodon.social/@probablyfine

**Comment by Bekabyx** [comment]
Hopefully they'll all use the proper account migration feature! If they don't then we'd have no way of tracking it.

**Comment by symroe** [comment]
It looks like there's a JSON endpoint with a `moved` key:

https://mastodon.social/api/v1/accounts/lookup?acct=probablyfine

Not sure if that's standard to all instances, but I imagine it will be. It [exists on my current server](https://mastodon.me.uk/api/v1/accounts/lookup?acct=symroe)

**Comment by Bekabyx** [comment]
@symroe I've checked my instance and it [doesn't seem to be working](https://pythonist.as/api/v1/accounts/lookup?acct=bekabyx) there, and I'm also not getting results for the octodon.social instance. I wonder if it's a config option that the server owner can set to enable/disable the lookup.

**Comment by tomresing** [comment]
Sounds like you may be interested in "supporting the Move activity" as described in the following quote from [Moving or leaving accounts](https://docs.joinmastodon.org/user/moving/) in Maston help. Unfortunately, I don't know what's involved in said support.
> Moving your account is the same as redirecting your account, but it will also irreversibly force everyone to unfollow your current account and follow your new account, if their software supports the Move activity. Your posts will not be moved, due to technical limitations.
