### ISSUE TITLE
Incorrect SOPN Brentwood

### ISSUE THREAD

**Issue by robintchap** [DemocracyClub/yournextrepresentative#1999]
The SOPN is for Ingatestone and Fryerning Parish not Ingatestone, Fryerning and Mountnessing ward.

https://candidates.democracyclub.org.uk/elections/local.brentwood.ingatestone-fryerning-and-mountnessing.2023-05-04/sopn/

**Comment by pmk01** [comment]
Hi Robin,

Thanks, this has been fixed! In the future, the best way to raise this sort of thing is in our Slack https://slack.democracyclub.org.uk/ or else via email.
