### ISSUE TITLE
Add flag for candidates deselected post-SoPN day

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/yournextrepresentative#2065]
Sometimes candidates do bad things and get deselected, but they are already on the ballot paper. We should reflect this somehow.

**Comment by pmk01** [comment]
A flag of some kind on the candidate's box on the ballot paper, and then something on the candidate profile:

"This candidate has been deselected by their party, but will remain on the ballot paper. [Learn more.](https://www.hackneycitizen.co.uk/2019/11/24/hackney-north-lib-dem-candidate-dropped-clearly-offensive-tweets/)"

(we'd need to link it to a specific election, however...)

**Comment by VirginiaDooley** [comment]
> A flag of some kind on the candidate's box on the ballot paper, and then something on the candidate profile:
> 
> "This candidate has been deselected by their party, but will remain on the ballot paper. [Learn more.](https://www.hackneycitizen.co.uk/2019/11/24/hackney-north-lib-dem-candidate-dropped-clearly-offensive-tweets/)"
> 
> (we'd need to link it to a specific election, however...)

Presumably you want to be able to mark this in the admin panel as well?

**Comment by pmk01** [comment]
Yes, mark in Candidates admin, to display on WCIVF and the API. This has been requested by a political party which uses our API.
