### ISSUE TITLE
Small issues with bulk adding forms

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#208]
Couple of things:

1. After adding a new name I get this that looks a bit ugly:
![screen shot 2017-05-11 at 13 02 54](https://cloud.githubusercontent.com/assets/242329/25948168/484d4e9e-364a-11e7-94d9-3ea9e2d013b8.png)

2. I didn't know what the "review" button did at the top of the form. I think it needs something like "There are more candidates listed / enter them below" and "There are no other candidates listed on the nomination paper"
![screen shot 2017-05-11 at 13 03 16](https://cloud.githubusercontent.com/assets/242329/25948188/57d4c126-364a-11e7-98f3-6e05720095e0.png)

**Comment by mhl** [comment]
Oh, I think was 1 was something we'd spotted before and @zarino was did a fix for (a missing clearfix) - did that change not get in, or is this a reversion?

**Comment by JoeMitchell** [comment]
I don't think we need 15 person fields. Only likely to be missing 2-3 candidates per ward I suspect. So, maybe, say 5 person fields to cover everything?

**Comment by JoeMitchell** [comment]
I also wonder if there's a way to make the seven-step instructions more attractive (and thus better read)? 

If I read the instructions, I understand the 'Review' button; if I don't, it looks weird. Let's rename it the 'Okay, I think we've got everyone' button. (Also, is it obviously a button?)

**Comment by chris48s** [comment]
> I don't think we need 15 person fields

Conversely, in the local elections, I found there were some wards where 15 wasn't enough and I had to do 2 passes to get all the candidates on the SOPN.

**Comment by mhl** [comment]
There's a suggestion (with a JSFiddle) for dealing with the problem of needing very different numbers of entry boxes here: https://github.com/mysociety/yournextrepresentative/issues/840#issuecomment-299444469

**Comment by mhl** [comment]
I made a pull request to fix the formatting issue with the first added alternative name: https://github.com/DemocracyClub/yournextrepresentative/pull/212

**Comment by michaeljcollinsuk** [comment]
@symroe having looked in to this, the page has been improved so that I don't think the original issue is still relevant. But the page could still be improved so I open an new issue for this

**Comment by michaeljcollinsuk** [comment]
New issue here #1364
