### ISSUE TITLE
Candidate rank isn't working

### ISSUE THREAD

**Issue by VirginiaDooley** [DemocracyClub/yournextrepresentative#2168]
https://candidates.democracyclub.org.uk/elections/local.st-albans.st-peters.by.2023-06-13/

`None` appears in the results table as well as individually in the person detail/candidacy results

<img width="738" alt="Screenshot 2023-08-24 at 6 56 46 AM" src="https://github.com/DemocracyClub/yournextrepresentative/assets/7017118/5b7752d4-dc2e-46a7-8cdb-b2bbe9a9a5dd">

**Comment by pmk01** [comment]
Closed as duplicate: https://github.com/DemocracyClub/yournextrepresentative/issues/2173
