### ISSUE TITLE
Rank is None for past elections

### ISSUE THREAD

**Issue by VirginiaDooley** [DemocracyClub/yournextrepresentative#2173]
Perhaps a known issue - candidate described as being placed "None / 4 candidates" when it should be "2nd / 4 candidates" etc - seems to be on all pages, will add two examples...

[Slack Message](https://democracyclub.slack.com/archives/C04U18ETS/p1693924361788809?thread_ts=1693924361.788809&cid=C04U18ETS)

**Comment by pmk01** [comment]
I think this only affects elections held before you implemented the change:
https://candidates.democracyclub.org.uk/elections/local.middlesbrough.ayresome.by.2023-08-17/
https://candidates.democracyclub.org.uk/elections/local.middlesbrough.nunthorpe.2019-05-02/

It also only appears on YNR so is low priority.

**Comment by VirginiaDooley** [comment]
Closed with https://github.com/DemocracyClub/yournextrepresentative/pull/2208
