### ISSUE TITLE
Do not index tag isn't added to ballot pages when marked on a candidate

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/yournextrepresentative#2243]

**Comment by VirginiaDooley** [comment]
@pmk01 Do you have an example of this bug?

**Comment by pmk01** [comment]
https://candidates.democracyclub.org.uk/person/80987/
https://whocanivotefor.co.uk/elections/local.rushmoor.empress.2021-05-06/empress/
https://whocanivotefor.co.uk/elections/local.hampshire.farnborough-south.2021-05-06/farnborough-south/

**Comment by symroe** [comment]
The tag is on these pages, so I don't think this is an issue any more

**Comment by VirginiaDooley** [comment]
I think it's that the query on the ballot page isn't working as expected.

**Comment by VirginiaDooley** [comment]
Scratch that, all is working as expected. 

![Image](https://github.com/DemocracyClub/yournextrepresentative/assets/7017118/4cd49231-18f7-4018-b25d-2dc25d5dc30b)
