### ISSUE TITLE
uk_results seem to be being lost on edits to person profiles

### ISSUE THREAD

**Issue by mhl** [DemocracyClub/yournextrepresentative#229]
There have been several instances for local council elections where people have spotted that the `uk_results` record of the number of votes they got disappears from the post page after and edit to that person's profile. For example:

* David Philip Griffiths here: https://candidates.democracyclub.org.uk/election/local.conwy.2017-05-04/post/UTE:W05000131/llandrillo-yn-rhos (spotted by @sjorford)

* Malcolm Hugh Delingpole here: https://candidates.democracyclub.org.uk/election/local.worcestershire.2017-05-04/post/CED:3357/tenbury (spotted by @sjorford)

*  Bob Jones here: https://candidates.democracyclub.org.uk/election/local.wiltshire.2017-05-04/post/UTE:E05008356/cricklade-and-latton

**Comment by JoeMitchell** [comment]
Another one, in case useful! 

- Martin Tod here: https://candidates.democracyclub.org.uk/election/local.hampshire.2017-05-04/post/CED:winchester-westgate/winchester-westgate (spotted by the candidate!)

**Comment by mhl** [comment]
The problem here is that `CandidateResult` objects have a `ForeignKey` field to `Membership`, but when you update a person [their `Membership`s are recreated](https://github.com/mysociety/yournextrepresentative/blob/07d6b80a9c41a3aa7e201858d74c84f11af5d43e/candidates/models/popolo_extra.py#L76-L123). (The code that recreates the memberships predated the `uk_results` app - at the time there was nothing that depended on them.)

I think the things to do are:

- [ ] Change `update_person_from_form` to preserve existing memberships and only make the minimal changes necessary (this would have a number of other advantages apart from fixing this bug)
- [ ] Write a script that goes through every `PostElectionResult` and checkes for any candidate for that post/election without a `CandidateResult` and makes a list of them
- [ ] Manually put back each of the results from that list (or if there are a huge number, retrieve them from an old backup)

**Comment by pmk01** [comment]
I don't know what this was really about becuase the links are too old to work, but this is not an issue anymore as far as I am aware.
