### ISSUE TITLE
separate an image download command out from candidates_import_from_live_site

### ISSUE THREAD

**Issue by mhl** [DemocracyClub/yournextrepresentative#233]
Not everyone needs the images for development, and it's a lot of data to download. In addition, sometimes we set people up with a database dump from someone else's development instance - if the media and database syncing were decoupled that would help these people, since they could then just bring in the images referred to in their local database (or the command could let you include some subset - e.g. just images of party logos + people standing in current elections).

**Comment by symroe** [comment]
We've added a flag to the command now. It doesn't download images on it's own (i.e it still needs a clean database) but I'll call this done for now.
