### ISSUE TITLE
Person fields in the API should be dervied from the *Field models in the database

### ISSUE THREAD

**Issue by mhl** [DemocracyClub/yournextrepresentative#238]
The original bug report this is addressing is that the `biography` field (used as the Statement to Voters) isn't present in the API output (except as embedded in the `versions` data).

The problem here is that the fields in the `PersonSerializer` and `NoVersionPersonSerializer` classes are hardcoded: https://github.com/DemocracyClub/yournextrepresentative/blob/1c603b47f5d7906c8c8b9ee0b9576290dfc1ccbc/candidates/serializers.py#L317-L385 rather than being based on SimplePopoloField and ComplexPopoloField. (The ExtraField values are already included.)

The field list could be created by the serializer dynamically: see the answers here: http://stackoverflow.com/q/17552380/223092 and http://www.django-rest-framework.org/api-guide/serializers/#dynamically-modifying-fields

**Comment by symroe** [comment]
I'm closing this as we're changing the way we deal with fields quite a bit.
