### ISSUE TITLE
candidates_cache_api_to_directory should prune old timestamped directories

### ISSUE THREAD

**Issue by mhl** [DemocracyClub/yournextrepresentative#263]
The root partition on the YNR server filled up this morning - this was largely due to the candidates_cache_api_to_directory command being run several times a day, but the script not pruning old timestamped directories at all.

**Comment by mhl** [comment]
Fix here: https://github.com/DemocracyClub/yournextrepresentative/pull/268

**Comment by symroe** [comment]
https://sentry.io/democracy-club-gp/ynr-v9/issues/277447383/

**Comment by symroe** [comment]
This was a) fixed some time ago and b) redundant now we're using S3
