### ISSUE TITLE
"I can't find this information, give me something else" button gives Server Error (500)

### ISSUE THREAD

**Issue by EdwardBetts** [DemocracyClub/yournextrepresentative#272]
I clicked the button marked "I can't find this information, give me something else". The site sent me to https://candidates.democracyclub.org.uk/tasks/couldnt_find_field/19848/ and showed Server Error (500).

**Comment by symroe** [comment]
I expect this has been fixed now, but regardless we've removed the task link from the home page and are about to re-write it. I'll call this "fixed" for the time being!
