### ISSUE TITLE
Search for Rebecca Thackray = 500 Error

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#277]
Searching for Rebecca, Thackray or combined = https://candidates.democracyclub.org.uk/search?q=rebecca+thackray returns a 500 error 

The discussion on Slack as follows: 

chris48s
>`NoReverseMatch: Reverse for 'person-view' with arguments '('', u'')' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'person/(?P<person_id>\\d+)(?:/(?P<ignored_slug>.*))?$']`

jonathanf
>Something related to her alternate name? https://candidates.democracyclub.org.uk/search?q=becca+thackray works while both https://candidates.democracyclub.org.uk/search?q=rebecca and https://candidates.democracyclub.org.uk/search?q=thackray fail.

mark
>that's probably the search index and the database getting out of sync at some point

**Comment by JoeMitchell** [comment]
And this from the candidate:

>I have tried a couple of times to enter my data. I can sign in OK and completed the profile & data. But access is denied.

**Comment by mhl** [comment]
This is typical of an error you get when a result from the Elasticsearch index references a Django object that has somehow been deleted without triggering a correspoding removal from the Elasticsearch index. In this case it's for someone called Rebecca:

```
In [5]: for sr in SearchQuerySet().filter(text__contains='rebecca'):
    print sr.object
   ...:     
Rebecca Knowles
Rebecca Bell
Rebecca Findlay
Rebecca Fox
Rebecca Breese
Rebecca Johnson
Rebecca Harris
Rebecca Rye
Rebecca Fraser
Rebecca Knox
Rebecca Plenderleith
Rebecca Taylor
Rebecca Pow
Object could not be found in database for SearchResult '<SearchResult: popolo.person (pk=u'35175')>'.
None
Rebecca Hutcheon
Rebecca Evans
Rebecca Singh
```

The current largest person ID in the database is 35174:

```
 In [17]: Person.objects.order_by('-id')[0].id
Out[17]: 35174
```

So presumably this mismatch was created by some attempt to create a person recently.

I tried to update the index with Haystack's admin command for this:

```
./manage.py update_index --remove
Indexing 33419 People
Failed to query Elasticsearch using '*:*': TransportError(500, [...] u'reason': {u'reason': u'Result window is too large, from + size must be less than or equal to: [10000] but was [11000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.', u'type': u'query_phase_execution_exception'}, u'shard': 0}], u'root_cause': [{u'reason': u'Result window is too large, from + size must be less than or equal to: [10000] but was [11000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.', u'type': u'query_phase_execution_exception'}], u'grouped': True, u'reason': u'all shards failed', u'phase': u'query', u'type': u'search_phase_execution_exception'})
Traceback (most recent call last):
  File "[]/env/local/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 516, in search
    _source=True)
  File "[]/env/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 70, in _wrapped
    return func(*args, params=params, **kwargs)
  File "[]/env/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 388, in search
    params=params, body=body)
  File "[]/env/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 274, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore)
  File "[]/env/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 55, in perform_request
    self._raise_error(response.status, raw_data)
  File "[]/env/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 83, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
[...]
TypeError: 'NoneType' object is not iterable
```

We could manually remove just that object instead if that error can't easily be resolved - I don't have time to investigate further at the moment, though.

**Comment by symroe** [comment]
This seems to be working now, so I expect it was some sort of sync error as Mark suggested. I'll mark it as closed as there's no obvious next steps, or clues as to why it happened.
