### ISSUE TITLE
Flag all edits to candidate statements for review

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#283]
I feel like candidate statements are particularly vulnerable to defacement, etc - they're presented on WhoCIVF as being a direct message from the candidate and the barrier to entry for trolling/defacement of editing this text is much lower than would be necessary to, for example, set up a parody twitter or facebook account.

Personally I think it is probably reasonable to flag all edits which touch the statement field for review (in particular changes to a non-empty statement and especially those by a user other than the statement creator), but it would be interesting to get a feel for volume - how many such edits occurred in the last week that weren't already flagged by other rules? Do others agree?

**Comment by JoeMitchell** [comment]
Yep, I think this makes sense. We had about 1,000 candidate statements at the GE in six weeks.... so that's quite a few to look at ... But it's easy to spot an obviously defaced one...
