### ISSUE TITLE
lots of candidates for parl.2017-06-08 seem to have elected=False set already

### ISSUE THREAD

**Issue by mhl** [DemocracyClub/yournextrepresentative#287]
If you look down the `elected` column of:

https://candidates.democracyclub.org.uk/media/candidates-parl.2017-06-08.csv

... lots of candidates seem to have a value of `False`, even though the election hasn't happened yet. I'm not sure how this would have happened.

**Comment by mhl** [comment]
On a quick look, this line is wrong:

https://github.com/DemocracyClub/yournextrepresentative/blob/f1da947419ffbdaf1b887ebd092dc1058c9ed4ae/bulk_adding/views.py#L186-L193

... which would mean that people who were found at the point of review in the bulk adding process to already exist in the database would have a new candidacy created with `extra.elected` set to `False`, not `None` as they should have been.

**Comment by symroe** [comment]
I'm happy with you setting them to `None` on prod

**Comment by mhl** [comment]
We resolved this before the election (using the command in the linked PR)
