### ISSUE TITLE
API: expose list of posts relating to an election

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#300]
It would be useful to be able to get a list of the posts relating to a given election. Perhaps a suitable call would be something like https://candidates.democracyclub.org.uk/api/v0.9/posts/?election=local.cannock-chase.2017-09-07

**Comment by symroe** [comment]
In the `next` API, when #1044 is merged, the `elections` endpoint will have a list of ballots related to it, and be keyed off the election slug. 

We will also have various filters on the `ballot` endpoint.

I suspect the relationship between `election` and `ballots` is what you're really after in this issue, or are you actually after `posts`?

**Comment by chris48s** [comment]
I mean, when I raised this issue in Aug 2017 I probably _did_ actually mean posts, but things have moved on..
