### ISSUE TITLE
Display date of the election on every /post page

### ISSUE THREAD

**Issue by jf1** [DemocracyClub/yournextrepresentative#303]
Users shouldn't need to look at the URL to confirm the date of the by-election that they're dealing with.

![image](https://user-images.githubusercontent.com/4711363/30125530-925fb36c-9330-11e7-92f4-87ac206e380e.png)

**Comment by jf1** [comment]
For context, there have been two recent deaths in this Salford ward, so another by-election will be announced soon and there's potential for the later Notice Of Election to be published before the first by-election's polling day, so the two by-elections would 'overlap' from DC's perspective.
http://salfordsoapbox.co.uk/page/local/veteran-councillor-joe-murphy-claremont-passes-away-r163/
http://www.manchestereveningnews.co.uk/news/greater-manchester-news/shock-after-inspirational-councillor-found-13576261

**Comment by jf1** [comment]
Nice to see this is ready - it was shouted out (by someone other than me!) when a colleague showed a page from a previous year's election. Is there any way to preview the proposed changes, or be notified once they're live?

**Comment by VirginiaDooley** [comment]
Completed with https://github.com/DemocracyClub/yournextrepresentative/pull/2170
