### ISSUE TITLE
Disappearing posts

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#311]
@sjorford wrote:

> what happened here? https://candidates.democracyclub.org.uk/numbers/election/local.hartlepool.2016-05-05/posts
> there should be a lot more posts - see https://candidates.democracyclub.org.uk/upload_document/1424/
> no candidacy is showing on the candidate pages, but the history shows it was added https://candidates.democracyclub.org.uk/person/10288

@symroe wrote:

> I expect it’s one of the problems pre move to using the `PostExtraElection` model, but I don’t know

**Comment by sjorford** [comment]
The 2016 Hartlepool election seems to have all been restored now. Was the underlying issue the same as #257?

**Comment by symroe** [comment]
These must have been fixed when I did https://github.com/DemocracyClub/yournextrepresentative/pull/1183 - bacially I ended up going back through the version history to pull out memberships we didn't have in the database.
