### ISSUE TITLE
prevent users from locking areas where they have added all the candidates themselves

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#312]
..or maybe make it impossible to do this if you have the usual 'lock area' permission, but have a special 'lock own areas' permission which only super admins have - just in case?

**Comment by sjorford** [comment]
gregorywilliams has done this for the last couple of by-elections, e.g. [Wiveliscombe and West Deane](https://candidates.democracyclub.org.uk/election/local.taunton-deane.2018-04-05/post/DIW:E05006883/wiveliscombe-and-west-deane)
