### ISSUE TITLE
Upgrade to Django 1.11

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#321]
Django 1.8 is an LTS release and still gets security patches but it is EOL in April 2018 - see https://www.djangoproject.com/download/

Given YNR still runs on python 2.7 in prod, lets target getting on to Django 1.11 as a first step

**Comment by symroe** [comment]
cd7ac0a7ddf0d3b7b2d146dc30bf00c47cf36cb7 moved us to Django 1.9. I reckon I'll bump the versions one at a time and keep the commits for them grouped in a PR per version.

**Comment by symroe** [comment]
Related, there are a few places that catch `ImportError` to support different Django errors. Check these when upgrading.

Some of these relate to #491 as well.
