### ISSUE TITLE
/search throws KeyError

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#413]
https://sentry.io/democracy-club-gp/ynr-v9/issues/443056734/

https://candidates.democracyclub.org.uk/search throws `KeyError: 'query'` with no query param.

Can't work out if this is actually a new bug or if it has been around a while but we've only just started seeing it

**Comment by pmk01** [comment]
https://candidates.democracyclub.org.uk/search looks good to me now?
