### ISSUE TITLE
static file errors

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#425]
https://candidates.democracyclub.org.uk/admin/

https://candidates.democracyclub.org.uk/static/admin/css/base.9f6547179ace.css
https://candidates.democracyclub.org.uk/static/admin/css/login.a846c0e2ef65.css

are both 404s

**Comment by chris48s** [comment]
Also https://candidates.democracyclub.org.uk/static/jsi18n/en/djangojs.e37eef1ffc63.js is a 404, which I think is the cause of https://sentry.io/democracy-club-gp/ynr-v9/issues/447469084/ and https://sentry.io/democracy-club-gp/ynr-v9/issues/447493052/ which are both client-side `'gettext' is undefined` errors.

**Comment by chris48s** [comment]
/admin is fixed by https://github.com/DemocracyClub/YNR_deploy/pull/6
https://candidates.democracyclub.org.uk/static/jsi18n/en/djangojs.e37eef1ffc63.js still throwing a 404

**Comment by symroe** [comment]
I reckon this might be useful http://django-statici18n.readthedocs.io/en/latest/faq.html#staticfiles-configuration
