### ISSUE TITLE
Site suggests that multiple candidates of the same party can be running for mayor.

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#45]
![candidates_for_greater_manchester_in_the_mayor_of_greater_manchester](https://cloud.githubusercontent.com/assets/8096305/22554859/9411186c-e959-11e6-91ff-5803129043e9.jpg)

Has this borrowed the ‘seats available’ default from locals, perhaps?

**Comment by symroe** [comment]
I think this is because I set `party_lists_in_use` on EE by mistake. 

This is because I thought that the SV voting system uses lists, when it doesn't.

I've unset it now.
