### ISSUE TITLE
Address YNR post by DC ballot ID

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#471]
As a user of Every Election and YNR I would like to be able to use Every Election ballot paper IDs in the YNR URL schema.

i.e: it should be possible to address (for example) https://candidates.democracyclub.org.uk/election/local.eastleigh.2018-05-03/post/DIW:bishopstoke using an alias like https://candidates.democracyclub.org.uk/election/local.eastleigh.bishopstoke.2018-05-03 or (or similar). We do now store ballot ids against elections imported from EE.

In order to properly implement this, as well as setting up a URL alias/redirect we also need to back-port DC-style election IDs onto elections which were covered in YNR before our ID schema was formalised.

**Comment by symroe** [comment]
I think this is done? Please re-open if not
