### ISSUE TITLE
Candidates on /moderation/suggest-lock aren't sorted by surname

### ISSUE THREAD

**Issue by gregorywilliams** [DemocracyClub/yournextrepresentative#488]
The candidates listed on the suggest-lock page aren't listed by surname:
![image](https://user-images.githubusercontent.com/1443772/38600870-9d0dc9e8-3d5d-11e8-9e7f-7e59319e612d.png)
This makes comparison with the SOPN that is listed by surname a little less efficient:
![image](https://user-images.githubusercontent.com/1443772/38600915-c2467b9c-3d5d-11e8-810e-8f2c014241cd.png)

**Comment by chris48s** [comment]
Are SOPNs always ordered alphabetically by surname?

If not, in the case where all candidates were added from the SOPN, ordering by when they were added is probably more likely to yield the same order as the SOPN.

I think this is mainly an issue in cases where somebody has added candidates to a post before nominations are published and then the rest have been filled in from the nomination paper.

At the moment we don't know the source, so we'd have to impose any ordering arbitrarily, but #461 would allow us to sort in one order if all the candidates were added via bulk add from SOPN and default to surname if some records were added one-by-one.

**Comment by gregorywilliams** [comment]
I've just reviewed and locked a few more constituencies. It's already proving noticably easier. Thanks.
