### ISSUE TITLE
Drop python 2 support

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#491]
It's being [deprecated after Django 1.11 anyway](https://docs.djangoproject.com/en/2.0/faq/install/#what-python-version-can-i-use-with-django), and [python2 doesn't have long left](https://pythonclock.org/).

**Comment by chris48s** [comment]
:+1: suggest we migrate prod to 3.x first before we stop running tests under 2.7

Am  right that there still a migration knocking about somewhere which stops you from initialising a clean DB under python 3 or did I make that up?

**Comment by symroe** [comment]
Yeah, there's something fishy going on with django popolo that I can't remember. Also running `makemigrations` on py3 makes a migration for each model that changes the label from a `u''` string to a native unicode object.

**Comment by symroe** [comment]
@chris48s found this helpful checklist that Django used: https://code.djangoproject.com/ticket/23919

**Comment by chris48s** [comment]
also maybe this https://github.com/asottile/pyupgrade

**Comment by symroe** [comment]
Prod is now on Python 3.5, so this is unblocked

**Comment by chris48s** [comment]
Major stuff is done, but there's still quite a lot of use of `six` and a few occurrences of `__future__` which could usefully be simplified, and still some of this sort of cruft:

https://github.com/DemocracyClub/yournextrepresentative/blob/da8eeef0729bef83d731d7d903fa23dc5abf4460/ynr/apps/compat/_compat.py#L27-L42

knocking about that we could usefully get rid of.

**Comment by symroe** [comment]
Fair enough – I was reading this as "drop _support_", and therefore it's done because I don't caure care if there's a bug in Python 2. But you're right that I could clean up a bit more before closing.
