### ISSUE TITLE
Use a word other than "Mark", which is a name, to indicate selecting a candidate

### ISSUE THREAD

**Issue by stuartlangridge** [DemocracyClub/yournextrepresentative#495]
When adding candidates for a local election, if a candidate with a similar name has stood in a previous election, a disambiguation page is shown which says things such as:

Candidate: Fred Bloggs
“The Conservative Party Candidate”
Some similar names have been found in our database.
If you're sure this is a new candidate, please select 'Add Fred Bloggs as a new person'. Otherwise, please check the similar names, and if it is the same person, select their name instead. The system will update them with the new candidacy.

* Add Fred Bloggs as a new person
* Mark Fred Bloggs (previously stood in Some Place in the 2017 County Council local election as a Conservative and Unionist Party candidate) as standing in This Place local election

Because "Mark" is a person's name as well as a verb, having sentences start with "Mark Fred Bloggs as..." is a bit confusing; it looks like it's naming someone called "Mark Fred Bloggs". Perhaps a better word could be chosen? "Select", or "set", or some better alternative?

**Comment by JoeMitchell** [comment]
This was also suggested by Si from mySociety at the Birmingham party, so thanks @stuartlangridge, for writing it up! 

I quite like 'Set'. I also like 'Label' or maybe 'Identify'. Does Label look too much like Mabel?

**Comment by jf1** [comment]
+1 for changing it, and in the example above +1 for `Set` (or maybe Select but I prefer Set)

The order should be amended too - if `Add` is the last resort it should appear at the end, so:
Please check the similar names, and if one is the same person, select **that** existing entry instead. The system will update them with the new candidacy.
If after checking the similar names you're sure this is a new candidate, please select 'Add Fred Bloggs as a new person'. 

Then the choices should be:
- **Set** Fred Bloggs (**who** previously stood in Some Place in the 2017 County Council local election as a Conservative and Unionist Party candidate) as ~~standing~~ **a candidate** in This Place local election **(also include date of poll?)**
- Add Fred Bloggs as a new person
