### ISSUE TITLE
Don't track users with do not track preferences 

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#500]
As per https://www.paulfurley.com/google-analytics-do-not-track/

Thanks @paulfurley!

**Comment by paulfurley** [comment]
Hooray!                                                                                                                                                                                                                                                                                                                From: notifications@github.comSent: 14 April 2018 9:17 amTo: yournextrepresentative@noreply.github.comReply to: reply@reply.github.comCc: paul@paulfurley.com; mention@noreply.github.comSubject: [DemocracyClub/yournextrepresentative] Don't track users with do not track preferences (#500)
