### ISSUE TITLE
Inconsistency on how many SOPNs need to be entered

### ISSUE THREAD

**Issue by Joe-C-London** [DemocracyClub/yournextrepresentative#502]
According to the [home page](https://candidates.democracyclub.org.uk/), there are 2762 ares with SOPNs imported, and 2706 areas entered.  This implies that there are 56 areas that have SOPNs that need to have data entered and locks suggested.

However, the [list of SOPNs that have no lock suggestions](https://candidates.democracyclub.org.uk/moderation/sopn-review-required/) is empty.  This renders users unable to work out which of the 56 SOPNs need entering so that this data can be entered.

**Comment by symroe** [comment]
Sorry about this! This was causes by some one locking areas before they'd had a suggested lock (the current system doesn't enforce two steps at the moment). 

To fix this I've unlocked all the areas, meaning they'll need double checking. All the candidates should be in, so it will be quick enough to do.

**Comment by Joe-C-London** [comment]
That makes sense.  I think there are a further ten that are in this state.
