### ISSUE TITLE
Add to other names if name field changes

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#507]
If a person's name changes then it's often useful to keep the previous name as an 'other name'.

**Comment by sjorford** [comment]
Adding the words "alternative names" to this issue so it is more easily searchable 🙂

**Comment by symroe** [comment]
Are there two cases we care about here?

1. A typo name change: in this case we don't care about keeping the other name, I expect

2. An actual name change (married name changed) or a name presentation change (First Middle Last over First Last), in this case we would want to keep both.

As a first pass I expect we can just store the other name in all cases, and allow manually deleting the name with a typo if we want to.

This in line with #639 would mostly be ok I think

**Comment by sjorford** [comment]
I think the majority of name changes are of type 2, so yes, keeping them all will be fine.

As an additional thought, if somebody changes the primary name to a name that is already in the alternative names field, we probably want to drop the (now duplicate) alternative name.
