### ISSUE TITLE
Allow reported turnout as a percentage

### ISSUE THREAD

**Issue by jwheare** [DemocracyClub/yournextrepresentative#509]
Not sure that a total value here makes sense as you can just sum the results. I'd actually already been inputing percentage data in this field as that's what the council reported. Also, this should  accept decimal values, e.g. 38.2%

**Comment by russss** [comment]
I think most people are putting percentages in here so we should probably just assume it's currently a percentage.

Note that you *can't* just sum the votes if it's a plurality-at-large election with multiple winners.

**Comment by jf1** [comment]
This issue might be better as "Direct users to enter turnout values as a percentage" although ideally this shouldn't be insisted on until users are also able to enter a "total valid ballots received" value for multi-seat elections.

Related: users should also be able to optionally enter an electorate value.

**Comment by IgnoredAmbience** [comment]
I have been adding the total results into this field by mistake (I'm submitting 3-candidate ward results) so some explanation should probably be given. I'm going back to fix my errors.

**Comment by michaeljcollinsuk** [comment]
Closed by #1474
