### ISSUE TITLE
Add a link to edit results after they've already been recorded

### ISSUE THREAD

**Issue by jwheare** [DemocracyClub/yournextrepresentative#510]
The edit URL can be worked out from the result page but there's no link if details need to be added or corrections made.

**Comment by jwheare** [comment]
I notice there's an edit link on e.g. this page:
https://candidates.democracyclub.org.uk/election/local.sheffield.2018-05-03/constituencies

but not on e.g. the post page:
https://candidates.democracyclub.org.uk/election/local.sheffield.2018-05-03/post/MTW:E05010857/beauchief-greenhill

**Comment by symroe** [comment]
Thanks for reporting @jwheare! I think I did this shortly after you raised the issue (the page you linked to has an 'edit' button), and forgot to comment and close this issue. Doing so now! :)
