### ISSUE TITLE
Incorrect Candidate Shown As Elected

### ISSUE THREAD

**Issue by IgnoredAmbience** [DemocracyClub/yournextrepresentative#512]
The Nonsuch Ward in the Sutton Council elections seems to have required a coin flip to elect the third candidate, with both receiving 1405 votes. The Candidates Page has shown the wrong one as being elected, and I can't see a way to select which won.

Election page:
https://candidates.democracyclub.org.uk/election/local.sutton.2018-05-03/post/LBW:E05000561/nonsuch

Official results (page 2 of the pdf):
https://www.sutton.gov.uk/download/downloads/id/3416/election_results_may_2018.pdf

**Comment by symroe** [comment]
Thanks!

I hacked this by entering one fewer votes for the candidate and then manually updated it after saving the results. Not ideal, but it sets the winners correctly.
