### ISSUE TITLE
bulk_adding by party page no longer shows existing candidates

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#536]
e.g. https://candidates.democracyclub.org.uk/bulk_adding/party/local.elmbridge.2018-05-03/PP90/

![image](https://user-images.githubusercontent.com/10633357/42293655-b3aa7a94-7fd3-11e8-9307-96207a11b078.png)

**Comment by symroe** [comment]
I think this will be fixed as part of #816. Wait until it's deployed to see. It's working locally, so I expect this is a search indexing issue that's been fixed since.
