### ISSUE TITLE
Allow pasting of white space into results fields

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#542]
The /uk_results/ page doesn't allow pasting of non-numeric data - but often when copying and pasting numbers from websites, there is white space copied along with the number, which stops the paste from working:

e.g. https://www.rutland.gov.uk/my-council/council-news/oakham-south-west-by-election-result/

![image](https://user-images.githubusercontent.com/10633357/42676062-7dc29294-866e-11e8-95e6-6cca418aa191.png)

**Comment by symroe** [comment]
I think this requires changing the input type away from `number` to a `text` input with a validation regex that allows numbers and spaces. We'll need to add a test to make sure the form is stripping the white space before trying to save the data.

**Comment by VirginiaDooley** [comment]
In trying to replicate this issue, I copied and pasted a numeric result with whitespace. The paste was successful and whitespace was stripped before save.
