### ISSUE TITLE
"use this data" links are broken

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#543]
Suspect there may be other issues of this nature. Also working out how to fix this might also fix OAuth ?

![screenshot at 2018-07-23 10 54 42](https://user-images.githubusercontent.com/6025893/43070152-f585a6f4-8e66-11e8-9a09-8789c7baf9ae.png)

**Comment by symroe** [comment]
To give a slightly longer explanation of how this is fixed:

In CloudFront we are setting `X-Forwarded-Host` to `candidates.democracyclub.org.uk` on the origin. This means that CloudFront will add this header to each forwarded request.

Django _can_ use this when it calls `_get_raw_host()`, but only if `USE_X_FORWARDED_HOST` is set to `True`.

As it defaults to `False`, Django was looking at the `Host` header, and coming up with whatever the ELB sets.
