### ISSUE TITLE
Search fails to find some candidates

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#545]
e.g. [Richard Frederick Boughton](https://candidates.democracyclub.org.uk/person/49054/richard-frederick-boughton) is in the system, but doesn't appear in a search for the full name or partial versions...

![image](https://user-images.githubusercontent.com/8096305/43193986-4184e2de-8ff9-11e8-86f9-07eaeac6a500.png)

And a similar problem with [Mick Kiff](https://candidates.democracyclub.org.uk/person/49049/mick-kiff) 

![image](https://user-images.githubusercontent.com/8096305/43194733-0a691372-8ffb-11e8-96e5-7af39ae1575f.png)

**Comment by symroe** [comment]
This was causes by the service that adds changes to the search engine not running since the server move. I've rebuilt the index now, meaning that all past edits (and people) are in the index, and from now on new edits should be added in near real time to the edits themselves.
