### ISSUE TITLE
Nice message if there are no results to input

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#555]
The "[area without results yet](https://candidates.democracyclub.org.uk/uk_results/no-results/)" is blank if no results are left to add. 

This makes it look like an error, rather than a happy state of the world. We should at least explain that the user needs to be happy (about this small thing, at least).

Better still, we invite the user to do other things, or tell them when the next results are likely to be ready to input (most Friday mornings, but let's check when the next election day is)

**Comment by pmk01** [comment]
https://github.com/DemocracyClub/yournextrepresentative/pull/1312
