### ISSUE TITLE
Allow winner to be set in elections with no poll

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#556]
In an uncontested election, a winner is selected with no poll.

At the moment we can work around that by setting the number of votes to 0. The only candidate will be marked the winner because they are first in a list of one e.g: https://candidates.democracyclub.org.uk/election/local.city-of-london.2018-07-12/post/LBW:E05009294/bridge This isn't strictly correct though because it implies there was a poll.

It would be useful to have a more explicit case to deal with uncontested elections.

**Comment by JoeMitchell** [comment]
Just another example (another City of London one, surrrprise) https://candidates.democracyclub.org.uk/election/local.city-of-london.2018-08-30/post/LBW:E05009293/bread-street

(I will mark it as zero votes for now)
