### ISSUE TITLE
Switch date format to UK style

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#56]
We're using the US style date format of MONTH, Day, YEAR, which is upsetting to me. 

We could go Chinese, cos they're objectively correct, or we could go British, cos that's what one might expect in Britain. Make Dates Great Again.

![candidates_for_all_posts_in_current_elections_](https://cloud.githubusercontent.com/assets/8096305/23016984/649e25de-f430-11e6-986b-40f4e6e61a72.jpg)

**Comment by symroe** [comment]
What's the best format? Can you give an example?
