### ISSUE TITLE
Sort candidates by vote count once results are in

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#635]
Up until we've got results, listing candidates in SOPN order is the most useful thing to do.

Once we've got results recorded, this table would be more naturally ordered by the 'votes' column, with the winner at the top:

![screenshot at 2018-09-10 14 36 03](https://user-images.githubusercontent.com/6025893/45300667-e6b73e00-b506-11e8-8e78-d62ab72b790d.png)

**Comment by VirginiaDooley** [comment]
I've checked several examples, this is already sorted as requested: 
![Screen Shot 2021-05-10 at 11 41 19 AM](https://user-images.githubusercontent.com/7017118/117647296-b2e3b900-b184-11eb-8add-15a2801cf4f0.png)

**Comment by chris48s** [comment]
This issue relates to the /elections page.

So for example if you look at the ballot page for
https://candidates.democracyclub.org.uk/elections/local.allerdale.aspatria.by.2021-05-06/ or
https://candidates.democracyclub.org.uk/elections/local.allerdale.christchurch.by.2021-05-06/
they're sorted with the winners at the top

..but if you look at the corresponding tables for Aspatria or Christchurch on https://candidates.democracyclub.org.uk/elections/local.allerdale.2021-05-06/ they are in SOPN order
