### ISSUE TITLE
Change 'below' to 'above'

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#65]
Sorry, I couldn't find the code to do this myself... but candidate search results to appear 'above', not 'below'. :) 

![image](https://cloud.githubusercontent.com/assets/8096305/23506351/c28603be-ff3f-11e6-9360-8d417a41ee2c.png)

E.g. https://candidates.democracyclub.org.uk/search?q=John+Williams

**Comment by andylolz** [comment]
Good spot. Looks like it’s here:
https://github.com/DemocracyClub/yournextrepresentative/blob/81c6d908/candidates/templates/search/search.html#L63

**Comment by JoeMitchell** [comment]
Don't thank me, thank Huw2 from that Wales. 

Ta for link — have made a Pull Request.
