### ISSUE TITLE
Full party list doesn't load on bulk_adding page

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#661]
e.g. https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.mid-and-east-antrim.2018-10-18/LGE:N10000804/

Clicking "Click to load more parties" in the drop-down fails to load https://candidates.democracyclub.org.uk/all-parties.json?partyset=ni with a `500` error (the same issue happens on other pages, so it's not just NI)

**Comment by symroe** [comment]
Just deployed the fix for this – can you confirm?

Thanks for reporting! :)

**Comment by sjorford** [comment]
Yep, working now - candidates are now in!
