### ISSUE TITLE
Consistent labels for 'Candidacies' section

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#67]
Low priority, but I've spotted a few issues in the Candidacies section. For example, here the Copeland label should be something like "2017 Copeland parliamentary by-election"

![image](https://cloud.githubusercontent.com/assets/8096305/23661244/0c3b6cda-0344-11e7-8521-f37c2e63592e.png)

Others miss the date too — this one for 2017 and 2016. 
![image](https://cloud.githubusercontent.com/assets/8096305/23661404/98ec5194-0344-11e7-81c0-d6cb0856ee4b.png)

**Comment by JoeMitchell** [comment]
Bumping this! Keep getting confused by things like this:

![image](https://cloud.githubusercontent.com/assets/8096305/24696296/e6855632-19e0-11e7-9285-b1d027164a03.png)

Would be great if all elections had years! (obvs can check the URL, but this would be betterer)

**Comment by jf1** [comment]
I've noticed similar inconsistencies across the site and a discussion on Slack about inexperienced users creating and naming elections - surely there's a way to standardise the text descriptors, eg:
Date (year for large elections, month and year for by-elections)
Area (UK, Greater Manchester Combined Authority, Suffolk County Council, etc)
Election type (General election, Mayoral election, local election etc)

**Comment by jf1** [comment]
![image](https://cloud.githubusercontent.com/assets/4711363/25236719/723cff26-25e0-11e7-9c16-0c7056a2393a.png)

I couldn't work out if this was the May 4 by-election or June 8 general election - only the [URL](https://candidates.democracyclub.org.uk/election/parl.manchester-gorton.2017-05-04/post/WMC:E14000808/manchester-gorton) clarified this.

This would be better as:
Known candidates for Manchester, Gorton in the UK Parliament by-election on May 4 2017
Or for the GE:
Known candidates for Manchester, Gorton in the UK Parliament general election on June 8 2017

**Comment by jf1** [comment]
From: https://democracyclub.org.uk/projects/election-ids/reference/
**Name and slug rules**
Slugification should be done following Django's slugify function with unicode disabled. The name for an area should be the official ONS name. For mayoral elections, the name of the city is used. For local elections, the council name is used with non-specific bits removed ('district council', 'city council', etc.).
**Example election identifiers**
Oxford City Council election	local.oxford.2016-05-05

I suggest that "with non-specific bits removed" is unhelpful as "Oxford City Council election" is specific whereas "Oxford election" isn't.

**Comment by pmk01** [comment]
https://github.com/DemocracyClub/EveryElection/issues/938

**Comment by pmk01** [comment]
Closing this as we've completely remade the candidacies section, and consistency problems are addressed in other issues.
