### ISSUE TITLE
Check for unused imports in CI

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#690]
In order to have a nice clean codebase we should start more automated code checks. A good start would be  `F401 Unused imports`. Here's how to do it:

1. [x] Run `flake8 --select F401 .`
1. [x] Manually fix all the cases found
1. [x] Add to the above command to CI scripts

**Comment by chris48s** [comment]
Also this codebase intentionally has a number of files which import loads of modules which are then not referenced for namespacing purposes e.g: https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/candidates/models/__init__.py

These might need a `# flake8: noqa` comment in them. They're _probably_ all going to be `__init__.py` files.
