### ISSUE TITLE
Deregistered parties appearing in the dropdown lists

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#70]
Naughty parties.

![image](https://cloud.githubusercontent.com/assets/8096305/23902628/bbd6f996-08b9-11e7-90db-5a77132aca46.png)

**Comment by JoeMitchell** [comment]
Sym and I chatted — we think this should be this way, because we might want to add historical candidates. The clever thing to do would be to add (Dereg'd in 20xx) to each of those British Unicorn Party(ies).

Looks a bit odd, admittedly, but unlikely to be seen by many / anyone — because of the cunning ranking of prepared answers for that party-input box.

**Comment by symroe** [comment]
Calling this fixed for two reasons:

1. Deregistered parties now have "Deregistered [date]" after their name: 
![screenshot 2017-04-12 17 03 31](https://cloud.githubusercontent.com/assets/242329/24967445/05265ad4-1fa2-11e7-977a-936a3fa09e14.png)

2. On the bulk add form deregistered parties are removed, assuming that we're only bulk adding current parties (this can be changed quickly if we decide to bulk add candidates from a previous election)
