### ISSUE TITLE
Update link from 'Add party info' box on candidate pages

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#710]
There's a nice call-to-action on the RHS of the candidate pages, see below. The 'p' in party doesn't need to be capitalised, but that's by-the-by. The button links to [a form](https://docs.google.com/forms/d/e/1FAIpQLSefxjlpi4UVK38CUGKZmZM3zjJO7hJfI58wSX6VZ0ifA54GAQ/viewform?entry.166120474=local.wirral.2018-11-22&entry.339427281=PP53) that presumably pumps the info into the LE2018 spreadsheet. 

![image](https://user-images.githubusercontent.com/8096305/48194834-fce64c80-e345-11e8-8068-1f569229ca60.png)

Should this instead link to an ongoing date-irrelevant spreadsheet? Or at least [the 2019 one](https://docs.google.com/spreadsheets/d/17x7lxujgkB570VY8eohZj4qQrBbeBmGFHjSVnGWifHk/edit#gid=0) for now... (But maybe we should make that the eternal spreadsheet, cos I reckon stuff doesn't change that much in terms of party contact details, year on year)

**Comment by symroe** [comment]
So this one is a bit tricky…

The form is pumping info in to the the 2018 sheet, yes, but even in 2018 is was a different tab to the one we were importing from. I've been manually copying and pasting the submitted data over.

I think we really need to move away from this manual / google forms set up and just have local parties in YNR properly. Before doing that, I don't think moving / recreating the form for 2019 adds much, given that it would still involve copying over to the sheet we import from.
