### ISSUE TITLE
Merged pages disappear from Recent Changes

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#758]
User **Apexharper** made four edits to two separate candidate pages at around 7am on 20 Jan - all four edits were appearing in `/recent-changes`.

I then merged `46170` into `49291` and now only the two edits to the latter page are listed:

![image](https://user-images.githubusercontent.com/10633357/51502948-60720900-1dd0-11e9-9cc1-5dde66917c74.png)

**Comment by symroe** [comment]
Do you remember if the other edits were photo uploads as well?

**Comment by symroe** [comment]
Fixed in #781
