### ISSUE TITLE
CSV for all candidates on 2nd May 2019

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#759]
Is it possible to generate a CSV for all elections on 2nd May? Currently I'm pulling down `candidates-all.csv` and then just filtering the ones for 2019-05-02, but that seems a waste when most of the candidates are for previous elections.

**Comment by symroe** [comment]
There are a some options here:

1. As per #499, have a flag somewhere that indicates we want a given election date to be combined in the CSV, but also in parts of the interface, like the `/elections/` page (and progress bars, SOPN adding, etc)

2. Import the "election" group ID in to YNR's `Election` model (e.g if the election ID is `local.foo.2019-01-01` then the group ID is `local.2019-01-01` and make a CSV on that. This would create a CSV for all `type, `date` pairs, including all by-elections.

3. Create a CSV for all elections per date

We could do all of course. 

@sjorford do you think you'd want here? Do you care about having all `mayor` and `local` candidates in a single file? In that case, option 3 might be the best?

**Comment by sjorford** [comment]
Yes, I think one file per date would be best - I'm tracking all the scheduled May elections together since there is frequently candidate overlap, so a single `candidates-2019-05-02.csv` containing `local` + `mayor` + `...` would be fine.
