### ISSUE TITLE
Wrong logo on the sharey twitter thing!

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#761]
![image](https://user-images.githubusercontent.com/8096305/51553487-e347a200-1e6a-11e9-803a-d5115c70423f.png)

😱 

Not sure if YNR uses the base-theme, but I also [made an issue about the same thing on Who/Where](https://github.com/DemocracyClub/dc_base_theme/issues/44).

**Comment by chris48s** [comment]
> Not sure if YNR uses the base-theme

It does not.

Suspect this wants swapping out:
https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/elections/uk/static/img/logo.png

We could probably usefully replace this too :smile: 
https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/elections/uk/static/img/apple-touch-icon.png
