### ISSUE TITLE
select2 dropdowns flashing when form regains focus

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#784]
This is weird:

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/10633357/52131908-ee9e8880-2635-11e9-92d7-1759de19a975.gif)

Good:
1. Click in a dropdown field
2. Select a value
3. Click in the next field
4. Nothing unusual

Bad:
1. Click in a dropdown field
2. Select a value
3. Click outside the browser window
4. Click in the next field
5. The first dropdown flashes briefly and the option under the mouse pointer is selected

It looks like when the select2 is enabled, the original select is hidden but the options still take up height?

![image](https://user-images.githubusercontent.com/10633357/52132427-0d514f00-2637-11e9-8feb-398f53a76ae2.png)

Same in Firefox and Chrome

**Comment by symroe** [comment]
Not to self: As a first, step upgrade `select2`. Two commits after the version we're using is a [commit to fix a bug with focus](https://github.com/select2/select2/commit/45ee7340e54259156b3b0ed38786f6a730810587) that might fix this.

**Comment by chris48s** [comment]
How do you get to the version of that form that has the Post drop-down on it?

Focus issues aside, the more worrying problem is the way that clicking a one form element is changing the _value_ in a different form element, isn't it?

**Comment by sjorford** [comment]
https://candidates.democracyclub.org.uk/person/49374 > Edit candidate > https://candidates.democracyclub.org.uk/person/49374/update

I don't actually have to click in a field to trigger the bug - if you click on the background of the page the dropdown still flashes, provided the place you click is under where the dropdown would be.

**Comment by chris48s** [comment]
In the screenshot you posted, the visible part of the URL is `https://candidates.democracyclub.org.uk/elections/local.windsor-and-maidenh...`, not `https://candidates.democracyclub.org.uk/person/49374/update` though.

**Comment by sjorford** [comment]
Oh, so it was - that's the new candidate form: https://candidates.democracyclub.org.uk/election/local.windsor-and-maidenhead.2019-05-02/person/create/?name=Arlene%20Carson

**Comment by chris48s** [comment]
I'm also having trouble reproducing this. Does this still happen if you disable your greasemonkey scripts?

**Comment by sjorford** [comment]
Yes, that's with Greasemonkey scripts disabled. I've reproduced it in Firefox, Chrome and IE (but not Edge), with scripts and adblockers all disabled. This is all on Windows 10 - I can't reproduce it on a Windows 7 VM.

**Comment by symroe** [comment]
@sjorford select2 updated now, can you see if it's solved / broken anything?

**Comment by sjorford** [comment]
No, I'm still getting the same behaviour 😞

**Comment by sjorford** [comment]
I think this has been fixed by recent design changes - at least, I can't reproduce it any more
