### ISSUE TITLE
bulk add by party doesn't show names if candidates already exist

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#791]
e.g: https://candidates.democracyclub.org.uk/bulk_adding/party/local.bradford.2019-02-07/PP52/

![screenshot at 2019-02-05 16-29-56](https://user-images.githubusercontent.com/6025893/52288099-684eb300-2963-11e9-94d8-2c6e62287b6c.png)

**Comment by symroe** [comment]
Calling this closed after all the SOPN work I've been doing – I think this would have been a search index problem.
