### ISSUE TITLE
Clarify that username will be public (so don't use email) 

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#80]
Probably a good idea...

Feedback from user: 

>Following an email alerting me to start uploading information about candidates I've just been doing that, however I didn't realise that my username would be plastered all over the pages.

>This wouldn't be a problem except I choose to use my email address as my username, now my personal email address is readily stamped all over the site and will be picked up I'm sure by search engines etc.

**Comment by JoeMitchell** [comment]
As @mhl suggests, we could do something cunning like

>reject usernames with `@` in them with a warning that it'll be public...

**Comment by symroe** [comment]
Two warnings added to the signup form now:

![screenshot 2017-04-13 09 29 18](https://cloud.githubusercontent.com/assets/242329/24996699/c64d79ca-202b-11e7-959e-afe8dad5da8d.png)

This is in staging so some testing would be helpful – I've had to upgrade the auth system to make this change happen, so I might have messed up other things in the process :/

**Comment by symroe** [comment]
(warning in the box is when someone adds a username with an `@` in, it's not there all the time)

**Comment by JoeMitchell** [comment]
Looks good Sym!

**Comment by JoeMitchell** [comment]
Happy to close this one!
