### ISSUE TITLE
Change text of 'existing candidates' screen on bulk add

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#81]
So this screen does tell lies, when it says 'An existing person with this name has been found...'

![screen shot 2017-04-07 at 12 29 45](https://cloud.githubusercontent.com/assets/8096305/24798629/d94fa544-1b8e-11e7-8b2f-8d44251ac79e.png)

Can we change the text to (something like): 

>Some similar names have been found in our database. If you're sure this is a new candidate, please select 'Add new person'. Otherwise, please check the similar names, and if it is the same person, select their name instead. The system will update them with the new candidacy.

**Comment by JoeMitchell** [comment]
Oh and we should probably get rid of the bullet points! Eek..

**Comment by davidmiller** [comment]
re. bullet points see the difference here: 

![screen shot 2017-04-07 at 12 46 05](https://cloud.githubusercontent.com/assets/17229/24798884/61c531a4-1b90-11e7-9843-43597dfc34e8.png)

![screen shot 2017-04-07 at 12 45 50](https://cloud.githubusercontent.com/assets/17229/24798890/648ebaa4-1b90-11e7-8957-13619ddfb718.png)
