### ISSUE TITLE
Merging versions with conflicting standing_in values

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#811]
I merged 48522 into 48512 - these were the versions I merged:

**48512** (version `2deae9851e4821fa`):

```
"party_memberships": {
	"local.waltham-forest.2018-05-03": {
		"id": "party:90",
		"name": "Liberal Democrats"
	}
},
"standing_in": {
	"local.waltham-forest.2018-05-03": {
		"name": "Hoe Street",
		"post_id": "LBW:E05000601"
	}
},
```

**48522** (version `00515d040486a761`):

```
"party_memberships": {},
"standing_in": {
	"local.waltham-forest.2018-05-03": null
},
```

The merged version took `party_memberships` from the target version and `standing_in` from the source, leading to this inconsistency:

```
"party_memberships": {
	"local.waltham-forest.2018-05-03": {
		"id": "party:90",
		"name": "Liberal Democrats"
	}
},
"standing_in": {
	"local.waltham-forest.2018-05-03": null
},
```

**Comment by sjorford** [comment]
I think something similar happened here: https://candidates.democracyclub.org.uk/person/4722/carl-walker

The merge history says 
>  At standing_in/local.worthing.2019-05-02 replaced "is known to be standing in Selden in the Worthing local election" with "is known not to be standing in the Worthing local election" 

The 2019 candidacy is still shown on the candidate's page:
![image](https://user-images.githubusercontent.com/10633357/54675328-43b73080-4af6-11e9-80a4-6b5852b682a1.png)

but not on the edit page:
![image](https://user-images.githubusercontent.com/10633357/54675354-4e71c580-4af6-11e9-9443-6ff268808f11.png)

**Comment by symroe** [comment]
Ok, there are two things going on here:

1. The inconsistent state of keeping the party against an election that the person isn't standing in – this is an easy fix.

2. The merge of two people where one has an election in the`not-standing` list and the other has a membership to the same election. In this case, it's not obvious what to do. I think keeping the membership is better than removing it, as it can always be removed in the future, after the merge.

**Comment by symroe** [comment]
Ok, deployed, this should be fixed now!
