### ISSUE TITLE
Data timeline isn't picking up results after being entered

### ISSUE THREAD

**Issue by magdamaciaszczyk** [DemocracyClub/yournextrepresentative#813]
The Vale of Glamorgan took place in February 2019 but the Data Timeline stopped on "Candidates verified".

URL: https://candidates.democracyclub.org.uk/elections/local.the-vale-of-glamorgan.rhoose.by.2019-02-14/

**Comment by symroe** [comment]
Thanks!

Changed the title, as the other steps are automatic / based on the data we have.

**Comment by it3986** [comment]
The timeline is still showing "Waiting for election to happen" even when results have been input.
e.g. https://candidates.democracyclub.org.uk/elections/local.welwyn-hatfield.hatfield-south-west.2019-05-02/
![image](https://user-images.githubusercontent.com/4873884/57443311-a6e75880-7245-11e9-9df8-cbe2c621357c.png)
