### ISSUE TITLE
Handle ResultEvent objects when merging or reverting

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#819]
Hello. 

There I was, attempting to reverse a bit of vandalism (for [this chap](https://candidates.democracyclub.org.uk/person/44084)), and what did I see? 

Server Error (500)

**Comment by symroe** [comment]
Sentry issue: [YNR-V9-CW](https://sentry.io/organizations/democracy-club-gp/issues/919818680/?project=169287&referrer=github_plugin)

**Comment by chris48s** [comment]
also can't merge
https://candidates.democracyclub.org.uk/person/38004 with
https://candidates.democracyclub.org.uk/person/19079
`Can't delete 'Jonathon David Taylor' with related objects: [<ResultEvent: ResultEvent object>]`
