### ISSUE TITLE
Login with email address, not username?

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#84]
This is a familiar piece of feedback: 

>2. I have no idea what my username is and can't figure out how to retrieve it

And several people try to log in using their email and don't even know that they're supposed to be using their username. 

Ergo, can we allow people to log in with their email address at the box below? 

![email_sign_in_](https://cloud.githubusercontent.com/assets/8096305/24857553/ac62e042-1de0-11e7-8d89-f071fe7070e4.jpg)

**Comment by mhl** [comment]
This should be easy to do by setting django-allauth's ACCOUNT_AUTHENTICATION_METHOD to ”“username_email”: http://django-allauth.readthedocs.io/en/latest/configuration.html

**Comment by jf1** [comment]
I can remember my username but not email, so please:
1. configure login to accept either username or email address, or
2. offer users a 'forgot username?' reminder system where entering their email address will trigger a reminder.

**Comment by mhl** [comment]
@jf1 The change I suggested would allow you to use either username or email address.

**Comment by jf1** [comment]
Thanks @mhl, panic over. I didn't readthedocs and was concerned by 'instead' in @JoeMitchell's request.

**Comment by JoeMitchell** [comment]
Darn, foiled again.

**Comment by symroe** [comment]
Deployed to the [staging site](https://stage.candidates.democracyclub.org.uk/). See Slack (or ask me) for authentication info. Seems to work for me.

**Comment by JoeMitchell** [comment]
I still see only 'username' on the staging site. (I know it's in the sentence above, but I basically don't read, I just look at forms...)

![image](https://cloud.githubusercontent.com/assets/8096305/24997414/7c0dac06-202e-11e7-9fb2-fc51e43bd019.png)

Can these become 'username/email' too?

**Comment by JoeMitchell** [comment]
Oh! And there don't seem to be enough characters available in the (to be known as) `username/email` box! I got stuck pretty soon!

**Comment by mhl** [comment]
I think this is fixed now - please reopen this and let us know if you see any problems.
