### ISSUE TITLE
More clearly show Sign up option on sign in page

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#85]
Feedback: 

>Couldn't find a way to register

Quick attempt at solution and light copy edits (also goes with issue #84 ) 

![light_reshuffle_of_sign_in_page](https://cloud.githubusercontent.com/assets/8096305/24858005/3e73ae20-1de2-11e7-94e6-202375d8d70e.jpg)

**Comment by jf1** [comment]
"Sign up for an account" seems better language than "... a DC Candidates account" which sounds like it's intended for candidates rather than general users.

+1 for moving the "Or sign up..." bit to the end/bottom of the page.

**Comment by symroe** [comment]
Adding this link for helpful ideas https://designpatterns.hackpad.com/Sign-in-aVfhGsMS3b2

**Comment by jf1** [comment]
Useful ideas in there. It recommends "Create an account" which I think is much better than "Sign Up" and "for a DC Candidates account".

Are you aware that the [password reset page](https://candidates.democracyclub.org.uk/accounts/password/reset/) can display "The e-mail address is not assigned to any user account" which can be used to harvest valid emails so would be better as "If we know the email address input@ddr.ess then an email with a password reset link will have been sent to it"

**Comment by symroe** [comment]
This whole thing is a bit of a mess, isn't it? We're asking the user to do one of 3 things:

1. Sign in *or* create a new account using social auth (these options do both in one!)
2. Sign in using an *existing* username and password
3. Create a new account using a username and password

This is the initial attempt at a redesign:

![screenshot 2017-04-12 18 04 17](https://cloud.githubusercontent.com/assets/242329/24969990/a93800b6-1faa-11e7-83e9-bf5204bd0ef0.png)

**Comment by jf1** [comment]
I'd make the first line: "Sign in with your **Democracy Club** email/username and password:"

Then the login box, then:
Or sign in* using your `Facebook account`, `Google account`, or `Twitter account`.
Or create a new Democracy Club account: `Create an account`

*This could be "sign up" if the process actually creates you a DC account (but I don't think it does, I'm just confused by your proposed first line).

**Comment by jf1** [comment]
Having investigated DC's create account process and considered [Amazon's system](https://designpatterns.hackpad.com/Sign-in-aVfhGsMS3b2#:h=Amazon) I feel combining 'sign in' and 'create account' on one page/form is the way to go, if practical. This means putting the set/confirm password form on a new page that users are redirected to from the confirmation email that they're sent.

Currently you need to click on a link in the email you receive:
![image](https://cloud.githubusercontent.com/assets/4711363/24973115/887b28f2-1fb5-11e7-9936-9b5fbdcb0ad1.png)

Then the page you're sent to has:
![image](https://cloud.githubusercontent.com/assets/4711363/24973079/6a7bbc40-1fb5-11e7-8c2f-a1d9858a8ee8.png)

Which feels superfluous, especially as there's no option to not confirm.

That step could be skipped and a single email confirmation page could ask the new user to enter and confirm their new password and accept the condition on the [user agreement page](https://candidates.democracyclub.org.uk/copyright-question?next=/).

If you're bothered about the 'Confirm' step then add "To create an account for user XX with email address something@some.com please enter a password and agree to the site's terms and conditions" at the top of this new `email confirmation` / `set password` / `agree to terms` page.

**Comment by JoeMitchell** [comment]
Yes, agree with Sym that it's pretty messy! But good is better than perfect, so I'd deploy what you have now Sym.

If I was being picky, I reckon we could lose the first sentence, which is quite long, and doesn't add much.
