### ISSUE TITLE
Entering invalid date can break the person pages

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#850]
A person `birth_date` of "1962-09-00" causes a 500 error

**Comment by symroe** [comment]
Sentry issue: [YNR-V9-D5](https://sentry.io/organizations/democracy-club-gp/issues/950045010/?project=169287&referrer=github_plugin)

**Comment by chris48s** [comment]
related: https://sentry.io/organizations/democracy-club-gp/issues/981347052/?project=169287
