### ISSUE TITLE
SoPN slugs and links

### ISSUE THREAD

**Issue by jf1** [DemocracyClub/yournextrepresentative#86]
On an [election page](https://candidates.democracyclub.org.uk/election/mayor.greater-manchester.2017-05-04/post/greater-manchester/greater-manchester) "Upload an updated Statement of Persons Nominated" is bigger aka more attractive than the "Nomination paper" link. Since people usually want the nomination paper link could the other link be shortened and diminished, eg to "Upload an updated version" ?

For the [SoPN page](https://candidates.democracyclub.org.uk/upload_document/6956/)'s address Is "/upload_document/" apt or would "/document/" or "/uploaded_document/" be more suitable?
Or c/should a url-rewrite make this eg /election/mayor.greater-manchester.2017-05-04/post/greater-manchester/greater-manchester/upload/6956

**Comment by jf1** [comment]
Agree neither of these are a priority and have just checked when not logged in - no confusion for standard users as there's no text and link displayed to upload another.

**Comment by symroe** [comment]
I've addresses the URL part of this issue in #792. I'm going to leave the design part of it for future work (it will be part of a wider design process)

**Comment by chris48s** [comment]
does #792 completely resolve this, or is there still stuff left to do on this issue?
