### ISSUE TITLE
Merging loses all versions

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#860]
I merged 50537 into 50536 and now the merged page shows no versions?

https://candidates.democracyclub.org.uk/person/50536/helen-cameron

**Comment by symroe** [comment]
This is odd.

1. Has this happened to other merged in the last ~month?
2. Can you think of anything about these people/person that might have caused this?

**Comment by sjorford** [comment]
I've not noticed this before.

The only odd thing about this case is that the person who created both (harry14) deleted the candidacy from 50537, and then Peter42 added the candidacy back. So both had the same 2019 candidacy when I merged them.

I saved a copy of 50537 if its of any use 
[50537.zip](https://github.com/DemocracyClub/yournextrepresentative/files/3024461/50537.zip)

**Comment by symroe** [comment]
We got a fun exception from it though:

> Exception: It looks like there was a bogus merge version for person with ID 50536; there were 0 merge versions and 2 person IDs.

Not sure why that exception didn't stop the merge though.

**Comment by symroe** [comment]
Sentry issue: [YNR-V9-D9](https://sentry.io/organizations/democracy-club-gp/issues/959753613/?project=169287&referrer=github_plugin)

**Comment by symroe** [comment]
Fixed now!
