### ISSUE TITLE
Duplicate elections/regions causes poor postcode search results

### ISSUE THREAD

**Issue by jf1** [DemocracyClub/yournextrepresentative#87]
There's no similar problem in WM ([this](https://candidates.democracyclub.org.uk/search?q=B1+2HB) works fine) so I suspect the problem is caused by [the list of current posts](https://candidates.democracyclub.org.uk/posts) including:
Greater Manchester
Liverpool City Region
and also:
Mayor of Greater Manchester
Mayor of Liverpool City Region

Unfortunately [this search](https://candidates.democracyclub.org.uk/search?q=M2+2AA) leads directly to https://candidates.democracyclub.org.uk/areas/combined-authority--combined-authority:greater-manchester-ca
Which states: Known candidates for Greater Manchester in the Greater Manchester - Oh no! We don’t know of any candidates in Greater Manchester for the Greater Manchester yet.

It should lead to [this post](https://candidates.democracyclub.org.uk/election/mayor.greater-manchester.2017-05-04/post/greater-manchester/greater-manchester).

Also, given [this election](https://elections.democracyclub.org.uk/elections/parl.manchester-gorton.2017-05-04/), results for [this search](https://candidates.democracyclub.org.uk/search?q=M12+4DF) should also include [this post](https://candidates.democracyclub.org.uk/election/parl.manchester-gorton.2017-05-04/post/WMC:E14000808/manchester-gorton).

**Comment by symroe** [comment]
Thanks @jf1. 

The posts were actually the wrong way around, with the ones with candidates in being older posts that mistook Liverpool and Manchester councils for the CAs. Candidates have been moved to the correct posts now, and the postcode searches work.

On the Gorton election, I'm looking in to it now.

**Comment by symroe** [comment]
Gorton fixed now, but you might not be able to see the fix if your browser has cached the redirect between the search and the old URL. Clearing a cache should make it work.

**Comment by jf1** [comment]
Thanks @symroe, postcode handled much better however I'm not convinced the GM election/post descriptions that are in use are correct.

They're: Known candidates for **Greater Manchester** in the **Greater Manchester**
I'd settle for: Known candidates for **Mayor of Greater Manchester** in the **Greater Manchester Combined Authority**

For Gorton it's currently:
Known candidates for **Manchester, Gorton** in the **Manchester, Gorton**
I suspect this would need agreement on standardised election names for it to become eg:
Known candidates for **Manchester, Gorton** in the **May 2017 Parliamentary By-election**

Also, there's a third election for some in GM - [this search](https://candidates.democracyclub.org.uk/search?q=M14+5JB) should lead to the Mayor, MP and a [ward by-election](https://candidates.democracyclub.org.uk/election/local.manchester.2017-05-04/post/MTW:E05000714/rusholme). It currently directs to [this](https://candidates.democracyclub.org.uk/areas/WMC--gss:E14000808,combined-authority--combined-authority:greater-manchester-ca) which shows all candidates for two elections on one page - would this be better as a list of the current elections for that postcode?

**Comment by jf1** [comment]
It's similar for LCR:
Known candidates for Liverpool City Region in the Liverpool City Region

I suspect the only way to standardise this for all elections would be to include a some post-type text, eg:
Known candidates for **Mayor of Liverpool City Region** in the **Liverpool City Region Combined Authority**
Post-type text would need two words to support: Mayor of; Councillor for; MP for; etc.

Anyway, I came back to highlight a Liverpool by-election - [this search](https://candidates.democracyclub.org.uk/search?q=L15+5BB) should also lead to [this by-election](https://candidates.democracyclub.org.uk/election/local.liverpool.2017-05-04/post/MTW:E05000912/wavertree).

**Comment by symroe** [comment]
Agreed on names, see https://github.com/DemocracyClub/yournextrepresentative/issues/67

I'll look at the by-election…

**Comment by symroe** [comment]
By-election: this is a bug with EveryElection where it's not attaching geographies to newly created elections.

I'll create an issue [over there](https://github.com/democracyclub/everyelection) for this.

**Comment by symroe** [comment]
(Oh, and it's fixed now)
