### ISSUE TITLE
Merging and duplicate alternative names

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#881]
> if I merge two people with different names, I end up with the name from the duplicate person in both the "name" and "alternative names"

> I would expect the original name in "name" and the duplicate's name in "alternative names"

**Comment by symroe** [comment]
here's an example https://candidates.democracyclub.org.uk/person/49378/emma-adams

**Comment by chris48s** [comment]
version `3c98d0b2db51e5f5` is straight after the merge on that person

**Comment by sjorford** [comment]
This is still an issue - e.g. https://candidates.democracyclub.org.uk/person/49952/claire-elizabeth-douglas

**Comment by jf1** [comment]
I think this is quite a serious problem as we sometimes drop one of the names when merging.
