### ISSUE TITLE
Lock suggestions aren't being cleaned up after locking

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#884]
![Screenshot at 2019-04-04 22-09-09](https://user-images.githubusercontent.com/6025893/55588960-0625ea80-5727-11e9-959d-6fccaa9d27e7.png)

**Comment by symroe** [comment]
This was actually because they _were_ getting cleaned up!

On the home page we were only counting suggested locks, and they were getting cleaned up, so the number on the home page was too low and the header was correct. 

This means we're doing better than we thought! Woo!
