### ISSUE TITLE
SoPN parser: Capitalise 3rd letter of McAbc names

### ISSUE THREAD

**Issue by jf1** [DemocracyClub/yournextrepresentative#889]
If the first two letters are m and c then the third should be capitalised.

Separately, if the first three letters are m, a, c then the fourth could be capitalised, but I don't think this case is as clear cut as the mc one.

**Comment by VirginiaDooley** [comment]
@symroe I don't think this is an issue any longer. The name parser seems to be working well on both McX and MacX names:

![Screen Shot 2021-03-22 at 12 15 39 PM](https://user-images.githubusercontent.com/7017118/111988585-9625f000-8b08-11eb-9d5e-0c2e5aad41d3.png)

![Screen Shot 2021-03-22 at 12 15 19 PM](https://user-images.githubusercontent.com/7017118/111988598-98884a00-8b08-11eb-9608-10f3faf9aa2f.png)

**Comment by symroe** [comment]
@VirginiaDooley Did these names come from the SOPN parsing process? i.e, did you run a SOPN with a "Mc" name through the parser to produce the above?

If so - could you write a test case for it, as I don't think we have one at the moment. I reckon [this test](https://github.com/DemocracyClub/yournextrepresentative/pull/1372/files#diff-cd47c1fd81df8803c4537dd7ab9c8b52f64f3dfe3197104535817164a91d46fbR263) would be a good starting point for that
