### ISSUE TITLE
Adblocker flagging social login links as spam

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#89]
![adblock-issue](https://cloud.githubusercontent.com/assets/6025893/24951720/4520322a-1f6d-11e7-9d10-db3f9b5a7f12.gif)

See above demonstration. Bit of an odd one this as it doesn't happen consistently across all my browser/adblock setups. It might be that I have some particularly aggressive settings applied on this instance. I suspect this is also related to the same problem @davidmiller is hitting over in https://github.com/DemocracyClub/WhoCanIVoteFor/pull/89 (unconfirmed). Maybe there's nothing actionable to do here: If a user's content blocker is blocking our content then...meh. On the other hand:

1. Maybe there is something we can do to make our 'social' content look less spammy to content blockers
2. It is worth being aware of this in case someone else reports it/is confused by it

**Comment by davidmiller** [comment]
![screen shot 2017-04-12 at 16 08 42](https://cloud.githubusercontent.com/assets/17229/24964884/65912cc6-1f9a-11e7-9bdb-c804fd992c52.png)

So, it seems this is the culprit for me.

c.f. https://github.com/FortAwesome/Font-Awesome/issues/1799

**Comment by symroe** [comment]
At the moment they're being given an HTML class name that's the same as the auth provider (`<a href="#" class="facebook">`). I bet that's not helping and we're not using them, so I've removed them locally and we can test when it's deployed (changed as part of the changes in #85)

**Comment by chris48s** [comment]
ok. Let me know when its up and I'll give it a test. I have one browser/adblock combo where I can reliably reproduce this.

**Comment by JoeMitchell** [comment]
I'm seeing no changes...

![image](https://cloud.githubusercontent.com/assets/8096305/24997556/ea471b30-202e-11e7-8b6c-a4ea32bf0526.png)
