### ISSUE TITLE
SoPN parser: spot Co-operative when split over two lines

### ISSUE THREAD

**Issue by jf1** [DemocracyClub/yournextrepresentative#891]
The party suggestion is blank rather than Labour and Co-operative - note how the SoPN splits Co-operative at its -
https://candidates.democracyclub.org.uk/elections/local.trafford.sale-moor.2019-05-02/sopn/
This is the second occurrence - it had already happened with another Trafford SoPN

**Comment by VirginiaDooley** [comment]
@symroe I've tried to reproduce this one locally with ballot local.trafford.sale-moor.2019-05-02 and I don't see the issue: 

![Screen Shot 2021-03-22 at 11 36 30 AM](https://user-images.githubusercontent.com/7017118/111986671-2ca4e200-8b06-11eb-9a62-044f7634566e.png)

**Comment by symroe** [comment]
Good to know, thanks for testing - must have been fixed in some previous commit without us noticing that it closes this issue. I'll close it now
