### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'memberships'

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#893]
https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.manchester.2019-05-02/MTW:E05011380/review/ throws a 500

https://sentry.io/organizations/democracy-club-gp/issues/973159405/

**Comment by symroe** [comment]
Fixed in 8e32b8efa102b9a1f9682e70b5a8630cde91831e
