### ISSUE TITLE
MultipleObjectsReturned get() returned more than one Membership

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#894]
examples:

https://candidates.democracyclub.org.uk/person/52476
https://candidates.democracyclub.org.uk/person/52368/mark-hucker
https://candidates.democracyclub.org.uk/person/52415/steve-beatty
https://candidates.democracyclub.org.uk/person/52418/andrea-jane-powell
https://candidates.democracyclub.org.uk/person/6367/sue-cooper

all throw a 500

https://sentry.io/organizations/democracy-club-gp/issues/972322518

This could be the same root cause as #878 ?

**Comment by symroe** [comment]
All of these have been fixed.

**Comment by symroe** [comment]
By removing the memberships. They'll need re-adding correctly by someone, but they should all show in the lock / ready for data lists.
