### ISSUE TITLE
IntegrityError: Key (person_id, value_type)=(49646, twitter_username) already exists.

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#896]
https://sentry.io/organizations/democracy-club-gp/issues/857369163

This happened during last night's TwitterBot run. It might magically fix itself, but lets keep an eye on the next few twitterbot runs

**Comment by chris48s** [comment]
confirmed happening nightly

**Comment by jf1** [comment]
As a short-term workaround is it worth removing (for one night only) the twitter info from https://candidates.democracyclub.org.uk/person/49646/adam-newton
