### ISSUE TITLE
Bot doesn't parse two word surnames correctly

### ISSUE THREAD

**Issue by pjr11** [DemocracyClub/yournextrepresentative#899]
The second candidate listed on [this SoPN](https://candidates.democracyclub.org.uk/elections/local.gedling.calverton.2019-05-02/sopn/) is Pamela Ede Cooper, who appears in the PDF like this:
![image](https://user-images.githubusercontent.com/5487957/55626941-d1587880-57a4-11e9-87d0-2879d3c9f340.png)
However the bot parsed her name as "Cooper Pamela Ede". It would be nice if it could recognise two-word surnames like this.

**Comment by chris48s** [comment]
another example

https://candidates.democracyclub.org.uk/elections/local.braintree.yeldham.2019-05-02/sopn/

> VAN DULKEN
> Richard Michael

on the SOPN comes out as

> Dulken Richard Michael Van

**Comment by robgilliam** [comment]
Duplicated of #883
