### ISSUE TITLE
Password reset page confirms if email addresses belong to users

### ISSUE THREAD

**Issue by jf1** [DemocracyClub/yournextrepresentative#90]
The [password reset page](https://candidates.democracyclub.org.uk/accounts/password/reset/) can display "The e-mail address is not assigned to any user account" which can inversely be used to confirm valid emails or find out if someone is a user. It would be better as "If we know the email address input@ddr.ess then an email with a password reset link will have been sent to it."

The principle is highlighted in [here](https://designpatterns.hackpad.com/Sign-in-aVfhGsMS3b2#:h=Hackpad) (via #85):

> I've had pushback from dev based on security measures on patterns like this in sensitive data use cases. The argument being we are exposing personal information via the interface (you can ping addresses to see if they exist in the system).

**Comment by jf1** [comment]
The page also states: "Please contact us if you have any trouble resetting your password." but there's no link to https://democracyclub.org.uk/contact/ or obvious alternative.

**Comment by mhl** [comment]
This behaviour is from django-allauth - there's an issue discussing it on the repository for that project: https://github.com/pennersr/django-allauth/issues/1307

The key point there is that there is a usability / security trade-off with this behaviour - we do get quite a bit of mail from people having login problems (@JoeMitchell has passed a few on to me) and presumably would get more if there was a more helpful "Please contact us [..]" message as you suggest! Whether the gain in users getting a more helpful error messages to help with such problems is worth it versus the risk from being able to check if someone's email address corresponds to an account on this site is a question for discussion.

**Comment by VirginiaDooley** [comment]
A registered user is currently recognised in the password reset process whereas an unregistered user is prompted to create an account. 

> Hello from Democracy Club Candidates!
> 
> You are receiving this e-mail because you or someone else has requested a
> password for your user account. However, we do not have any record of a user
> with email [vcdooley@gmail.com](mailto:xxxx@gmail.com) in our database.
> 
> This mail can be safely ignored if you did not request a password reset.
> 
> If it was you, you can sign up for an account using the link below.
> 
> https://candidates.democracyclub.org.uk/accounts/signup/
> 
> Thank you for using Democracy Club Candidates!
> [candidates.democracyclub.org.uk](http://candidates.democracyclub.org.uk/)
> 

Calling this one done ✅
