### ISSUE TITLE
Homepage text issue

### ISSUE THREAD

**Issue by jf1** [DemocracyClub/yournextrepresentative#901]
There are two "full list of SoPNs" buttons/links on the homepage, and the first one isn't accurately described...

Button "See the full list of SoPNs" links to: https://candidates.democracyclub.org.uk/elections/?review_required=unlocked&has_sopn=1
-> Either change the link to https://candidates.democracyclub.org.uk/elections/?has_sopn=1 or keep the link as-is (preferable) and change its label to something like "List all elections with unprocessed SoPNs"

Text "The full list of SoPNs for the 2019 Local election can be found here" links to: https://docs.google.com/spreadsheets/d/1afmGJgJ6fKWmu7gCAxSlNTukO10O85GL13Ni8C54cXw/edit#gid=0
-> This text could be more specific, eg "The spreadsheet of 2019 Local Election SoPNs can be found here"

**Comment by symroe** [comment]
Reckon this one can be closed now – would have been a typo back then that will be changed before this May anyway (and it's not on the home page any more!)
