### ISSUE TITLE
UnsafeToDelete on merge

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#904]
https://candidates.democracyclub.org.uk/person/34573 and
https://candidates.democracyclub.org.uk/person/26002
is a legit merge, but raises `UnsafeToDelete`. This is probably usefully stopping us from accidentally doing terrible things, but would be useful to understand what we need to do so we can perform the merge in these situations

**Comment by symroe** [comment]
This is because there is still data in the old `Link` model with a GFK to Person.

This isn't needed any more, so we can truncate that table.

This should be done in a migration at some point.
