### ISSUE TITLE
Telling you about nomination forms

### ISSUE THREAD

**Issue by richardofsussex** [DemocracyClub/yournextrepresentative#906]
I checked my local area, to be told you don't have the nomination forms yet. They are actually on the MSDC site: https://www.midsussex.gov.uk/elections-voting/upcoming-elections/. There should be a link on the site so I can post you this information (without having to raise a GitHub issue!).

**Comment by symroe** [comment]
Thanks!

We do have a publicly editable Google Sheet here that we use to import them:

https://docs.google.com/spreadsheets/d/1afmGJgJ6fKWmu7gCAxSlNTukO10O85GL13Ni8C54cXw/edit#gid=0

I've just checked and the Mid-Sussex links are in. I've just kicked off an import job, so they should be in the system soon.

Thanks for letting us know!
