### ISSUE TITLE
Parser identifying ward/division by "first match", rather than "best match"?

### ISSUE THREAD

**Issue by robgilliam** [DemocracyClub/yournextrepresentative#911]
In Halton BC election for 2019-05-02, parser has added details for candidates for **Broadheath** ward as candidates for **Heath** ward (the latter appears later in the PDF).

**Comment by robgilliam** [comment]
![image](https://user-images.githubusercontent.com/1063408/55680224-c15ca800-590e-11e9-975d-9b55607724ba.png)

**Comment by robgilliam** [comment]
![image](https://user-images.githubusercontent.com/1063408/55680236-e3eec100-590e-11e9-8d89-a6645bb579da.png)

**Comment by robgilliam** [comment]
![image](https://user-images.githubusercontent.com/1063408/55680260-4c3da280-590f-11e9-985f-df1f746c171b.png)

**Comment by chris48s** [comment]
Other examples of incorrect ward matching:

> The SoPN parser has mixed up 'Sence Valley' and 'Valley' wards at https://candidates.democracyclub.org.uk/elections/local.north-west-leicestershire.valley.2019-05-02/sopn/
> The 'Sence Valley' ward is ok at https://candidates.democracyclub.org.uk/elections/local.north-west-leicestershire.sence-valley.2019-05-02/sopn/


> bot seems to have confused "Bulwell" and "Bulwell Forest" wards in Nottingham (https://static-candidates.democracyclub.org.uk/media/official_documents/local.nottingham.sherwood.2019-05-02/statement-of-persons-nominated.pdf)


> Bot has picked the wrong ward for Tadcaster, Selby (it picked Camblesforth and Carlton)
> https://candidates.democracyclub.org.uk/elections/local.selby.tadcaster.2019-05-02/sopn/

**Comment by chris48s** [comment]
> The bot has mistaken 'Swinton North Ward' for 'Winton' when separating the SoPN pages in https://candidates.democracyclub.org.uk/elections/local.salford.winton.2019-05-02/sopn/

**Comment by chris48s** [comment]
> The bot has mistaken 'Higham Ward' for 'Trench' when separating the SoPN pages in
> https://candidates.democracyclub.org.uk/elections/local.tonbridge-and-malling.trench.2019-05-02/sopn/

**Comment by symroe** [comment]
I'm closing this in favour of #873 where we have some more recent examples
