### ISSUE TITLE
Allow uncontested elections to be flagged when updating candidates

### ISSUE THREAD

**Issue by robgilliam** [DemocracyClub/yournextrepresentative#912]
Where an election is uncontested, i.e. the SoPN contains not more than the number of candidates for the election and a notice to that effect is shown in the council notices, it should be possible to flag the election as such when confirming candidates.

This would also go some way to addressing #556, as there would be no need to enter results for uncontested elections "on the night" (or from the official results).

**Comment by robgilliam** [comment]
(OK, I guess technically there isn't an SoPN for an uncontested election, just a "Notice of Uncontested Election" published at the same time, which lists the candidates elected unopposed)

**Comment by VirginiaDooley** [comment]
https://github.com/DemocracyClub/yournextrepresentative/pull/1708
