### ISSUE TITLE
Suggested lock page should be consistent in whether or not Alternate Names are shown

### ISSUE THREAD

**Issue by Joe-C-London** [DemocracyClub/yournextrepresentative#923]
Steps to reproduce:
1. Add candidate to election page
2. Add alternate name to said candidate
3. Lock election page
4. Go to lock suggestion page for said election
5. Add alternative name

Expected: Alternative name should be either present or absent both before and after
Actual: Alternative name is absent before adding in lock page, present afterwards

**Comment by symroe** [comment]
So on the suggestion page I'm hiding the alt-names inline until pressing "add alternative name" – I did this because I didn't want to break up the vertical spacing on the suggestion page – I find it easy to scan down the table and having more than one line per row would get confusing, I think.

Is this the same thing as you're talking about? Screenshots might help:

![Screenshot 2019-04-08 21 39 47](https://user-images.githubusercontent.com/242329/55755422-d8061a80-5a46-11e9-89b2-b512caa38414.png)

**Comment by Joe-C-London** [comment]
Here is a sample before:
![image](https://user-images.githubusercontent.com/18242738/55756877-7ba4fa00-5a4a-11e9-984a-c04f1b1196a7.png)

and after:
![image](https://user-images.githubusercontent.com/18242738/55756893-895a7f80-5a4a-11e9-8465-2854a1b55457.png)

**Comment by symroe** [comment]
Yeah, I see. I wanted to give some feedback that the name was added – do you think alt-names should always be there?

Or if never, then how to show that a name was added?

**Comment by Joe-C-London** [comment]
I think having it always there would make most sense.  It also saves me a couple of clicks to check whether said alternate name has been added.

**Comment by jf1** [comment]
I'm not convinced and think I side with Sym over Joe - it's more efficient if alternate names aren't shown/expanded by default...

With the increased volume and automation, I'm only interested in: body, area, name, party

I'd suggest that it's better to enable moderators to get through the queue as rapidly as possible, then if there's a mistake beyond the basic data I've specified above it can be picked up later, if anyone is interested enough to spot it.

**Comment by Joe-C-London** [comment]
The thing for me is, when the name on the SoPN matches an alternate name and not the main name, not showing it can actually slow me down quite considerably.

When, for whatever reason, I cannot easily view the PDF version beside the list, I will open it up in a second window overtop of where it normally would be. When the SoPN name matches an alternate, that for me is three or four extra clicks to verify this, plus an extra couple of seconds to regain my place on the SoPN once it's brought back up.

**Comment by VirginiaDooley** [comment]
The middle ground seems to be to add alt names by default earlier in the process, when a user is checking for matches with an existing candidate after entering or parsing a SoPN. I've closed this issue and created a new one to reflect this decision. 
https://github.com/DemocracyClub/yournextrepresentative/issues/1604
