### ISSUE TITLE
Change emblems for some parties

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#927]
Task: 

Edit this dict:

https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/parties/constants.py#L18

Adding emblem IDs for parties where we think the default emblem is currently wrong.

--------

DUP candidates are using old party emblem: https://candidates.democracyclub.org.uk/person/68686/james-cochrane
Should be using Embled ID 78 from http://search.electoralcommission.org.uk/English/Registrations/PP70

This might be a symptom of a wider issue about how we pick which emblem to use when there are several choices?

-------

Liberal party
PP54: 54

**Comment by symroe** [comment]
PP54: 54
