### ISSUE TITLE
Error 500 merging candidates

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#936]
The following pairs of candidates are giving `Error 500` when merging:

https://candidates.democracyclub.org.uk/person/57888/mike-balshaw
https://candidates.democracyclub.org.uk/person/46482/mike-balshaw

https://candidates.democracyclub.org.uk/person/50039/chris-davidson
https://candidates.democracyclub.org.uk/person/66008/chris-davidson

https://candidates.democracyclub.org.uk/person/11617/alan-davies
https://candidates.democracyclub.org.uk/person/54037/alan-davies

**Comment by fabianhoward** [comment]
Unsure if it's the same 500 (since I can't see the logs) but I also get it with:

Julia Kay Potts
https://candidates.democracyclub.org.uk/person/37806
https://candidates.democracyclub.org.uk/person/51020

Leonie Mathers
https://candidates.democracyclub.org.uk/person/4422
https://candidates.democracyclub.org.uk/person/4840

**Comment by symroe** [comment]
I think the underlying bug has been fixed here, but I've not checked all the people linked above.

**Comment by sjorford** [comment]
Yep, all of the above duplicates have now been merged 👍

**Comment by sjorford** [comment]
FYI the only pairs I know of that still give a `500` are

https://candidates.democracyclub.org.uk/person/9375/leslie-groves-williams
https://candidates.democracyclub.org.uk/person/35778/leslie-groves-wllliams

https://candidates.democracyclub.org.uk/person/3879/jonathan-mitchell
https://candidates.democracyclub.org.uk/person/36111/jonathan-mitchell

https://candidates.democracyclub.org.uk/person/8772/alex-curtis
https://candidates.democracyclub.org.uk/person/36160/alex-curtis
