### ISSUE TITLE
Google sign-in button broken?

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#94]
![](http://g.recordit.co/YdT5siJbDY.gif)

This probably didn't deserve a gif..

**Comment by JoeMitchell** [comment]
Works on live site..

**Comment by symroe** [comment]
I think that's because we have to register the site URL with Google and they're detecting that it's not the same. Bad that Twitter doesn't do this!

**Comment by JoeMitchell** [comment]
Cunning!
