### ISSUE TITLE
bulk entry

### ISSUE THREAD

**Issue by samsmith** [DemocracyClub/yournextrepresentative#95]
When bulk entering candidates and showing matches for previous candidates, show the body to which they stood last time (a Sam Smith on the other side of the country is unlikely to be the same one, but in the ward next door it is likely to be)

**Comment by symroe** [comment]
Thanks Sam, election and party now on the name. It's not the best place for it, but I think it's better than nothing:

![screenshot 2017-04-14 12 04 58](https://cloud.githubusercontent.com/assets/242329/25041824/d12ec756-210a-11e7-9555-7d03b13a3021.png)

**Comment by samsmith** [comment]
it's really useful. Would also be handy if under "add Mark as a new person" it also showed their party affiliation (as just entered on the form). It reduces a context switch back to the form to check which party they're standing for this time.

**Comment by symroe** [comment]
I've added this to the header under the candidate name. I think it's an improvement.
