### ISSUE TITLE
Apostrophe displays as â€™

### ISSUE THREAD

**Issue by WilfForrow** [DemocracyClub/yournextrepresentative#953]
Apostrophe displays as â€™, so I abbreviating <I have> to <I've> looks awful.

I've briefly googled it, and it's a character set issue.  I'm on a Mac, and they seemed to figure several times.  

Also, I pasted my text from another document, I think a google doc, which may have imported the wrong character set.  

You can see the example at  https://candidates.democracyclub.org.uk/person/43206 (that's me).

Great site, by the way.

**Comment by sjorford** [comment]
I think this is the same issue as https://github.com/DemocracyClub/WhoCanIVoteFor/issues/387

Actual apostrophes like `'` work fine, it's just curly apostrophes like `’` where there is a problem

**Comment by WilfForrow** [comment]
Yes, this looks the same as  DemocracyClub/WhoCanIVoteFor#387
I copied a 'straight' apostrophe and it worked fine, it's just curly apostrophes like ’ where there is a problem.
Would a quick fix be to replace all curly apostrophes with straight ones at save time?
Or if you find suspect characters/character sets in text, to display a hints box explaining how to  correct them characters (eg show sample characters to copy/paste)?
Happy to have this closed or merged with #387.
