### ISSUE TITLE
Old DUP logo is back

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#956]
Not sure how, but despite the change made in https://github.com/DemocracyClub/yournextrepresentative/pull/928 we seem to have reverted to the old DUP logo again both on YNR e.g: https://candidates.democracyclub.org.uk/person/68686/james-cochrane and WCIVF e.g: https://whocanivotefor.co.uk/elections/europarl.uk-northern-ireland.2019-05-23/

**Comment by it3986** [comment]
It looks like the most recent changes to /parties/constants.py have been pulled into the Master but have each failed the Travis Test and so have not actually been deployed to the Live sites.
Logo changes down to "National Front" are checked and still working but newer entries are not having a visible effect on YNR or WCIVF.
DUP, BNP and Animal Welfare Party should be overriden but are all still showing the default logo.

**Comment by symroe** [comment]
Fixed in 8ba5d5cda6fe43348fe7110c3eea1cae4d31e9fe
