### ISSUE TITLE
Christian Party shows Welsh Christian Party's logo

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#96]
As evidenced here: https://candidates.democracyclub.org.uk/person/6735/juliana-brimicombe — might also be happening for other CP candidates..

**Comment by symroe** [comment]
Fixed!

**Comment by symroe** [comment]
FYI, this requires us to do a couple of things:

1. Edit [this file](https://github.com/DemocracyClub/yournextrepresentative/blob/8d5f03633ddd1727e7810edd1d223f42c0f72d8b/elections/uk/management/commands/uk_update_parties_from_ec_data.py#L57) to add the description exactly as shown on [this page](http://search.electoralcommission.org.uk/English/Registrations/PP2893).

2. Delete previous images for this party

3. Re-run the party import on the server.
