### ISSUE TITLE
Update logo for Animal Welfare Party

### ISSUE THREAD

**Issue by it3986** [DemocracyClub/yournextrepresentative#960]
Add new constant value for logo ID for Animal Welfare Party (PP6166) as current default (id362) pulls through emblem including previous party name from 2007 rather than the 2014 or 2016 approved logo.

As discussed in WCIVF Slack Channel on 30/04/2019

Venessa Hudson is standing for this party in the EU Elections
https://candidates.democracyclub.org.uk/person/7400/vanessa-helen-hudson

**Comment by it3986** [comment]
Code changes made and merged into master but effect not yet seen on live WCIVF or YNR sites due to failure of this "Constants.py" file having new effects on sites - See Issue #956

**Comment by symroe** [comment]
Fixed in 8ba5d5cda6fe43348fe7110c3eea1cae4d31e9fe
