### ISSUE TITLE
Suspended Twitter accounts are removed by Twitterbot

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#978]
e.g. https://candidates.democracyclub.org.uk/person/7537 - the bot removed https://twitter.com/timg33 which is currently suspended. But suspensions may only be temporary, so we probably want to hold on to such accounts in case they come back.

**Comment by sjorford** [comment]
Two more examples:

https://candidates.democracyclub.org.uk/person/4859
https://candidates.democracyclub.org.uk/person/67795

<hr>

Note that TwitterBot updates the record, but doesn't update the version history:

![image](https://user-images.githubusercontent.com/10633357/63009368-438c4880-be7c-11e9-85ec-2faa763f7941.png)

![image](https://user-images.githubusercontent.com/10633357/63007485-a380f000-be78-11e9-8672-ea5a468aac64.png)

![image](https://user-images.githubusercontent.com/10633357/63009100-c1038900-be7b-11e9-96f8-d89bcd534331.png)

**Comment by sjorford** [comment]
Google sheet of recent Twitterbot edits:

https://docs.google.com/spreadsheets/d/1FhASVaVzgbv3rYzaOH7FBC8VVoCD5kVDvucd5NUcgik/edit?usp=sharing

**Comment by symroe** [comment]
Hard to know how to deal with this, the Twitter API says:

> If a requested user is unknown, suspended, or deleted, then that user will not be returned in the results list.

So, when we make the request to et info, there seems to be no way to know if an account is deleted or just suspended. 

To do: find if there's a way to detect this using the Twitter API - maybe using another call just for users that we think have been deleted.

**Comment by symroe** [comment]
This looks positive https://stackoverflow.com/questions/32806940/how-to-get-twitter-suspended-user-details

**Comment by VirginiaDooley** [comment]
We can: 
check the error code returned from the API call
filter code "63" for suspended accounts
return an appropriate message to twitterbot for suspended accounts
but not delete

**Comment by symroe** [comment]
This sounds good. I think this needs to only be for the accounts that we would remove, e.g in side [this loop](https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/twitterbot/management/commands/twitterbot_update_usernames.py#L43).

We might need to add some `sleep()` statements in there to stop getting rate limited, if we see a lot. I don't think we'll see loads though - you should be able to get an idea of this on this page: https://candidates.democracyclub.org.uk/recent-changes?username=TwitterBot
