### ISSUE TITLE
Nomination Paper page

### ISSUE THREAD

**Issue by samsmith** [DemocracyClub/yournextrepresentative#98]
where there are multiple wards on a single nomination paper (e.g. https://candidates.democracyclub.org.uk/upload_document/5008/ ) that page should say at the top Nomination Paper for XXX ward (and YY others), to reduce transcription errors where people don't notice there are multiple wards in a single paper and start in the middle

**Comment by pmk01** [comment]
Pretty sure this is fixed - we alert people to multiple nomination papers in one PDF, anyway.
