### ISSUE TITLE
Should "trusted to lock" users be allowed to edit memberships of locked ballots?

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#991]
At the moment if a user in the "Trusted to lock" group looks at a locked ballot page, they are able to make edits to the memberships (add or remove a candidate) without unlocking.

This has been the case for some time, but I think the user should be forced to unlock the ballot before making changes.

This means that all they'll be able to do after that is add a lock suggestion, meaning a second person will have to double check their work.

Before doing this, maybe we should expose some sort of log / messaging system for explaining why a person was added / removed from a locked ballot in the first place (it's likely to be a complex / non-trivial reason).

Are there any good reasons to keep this feature?

**Comment by JoeMitchell** [comment]
Only that it makes quick edits (mispelling etc) easy... but yes, this idea seems reasonable to me.

**Comment by chris48s** [comment]
If its a spelling edit, its an edit to the candidate profile, not a membership. This would only apply to asserting a candidate is/isn't standing in a locked ballot.

**Comment by JoeMitchell** [comment]
Ah, okay, sounds good.

**Comment by symroe** [comment]
Notes for future Sym:

This turned out to be a little more complex than expected. 

The problems are with the person add/edit form, and actually exists for a lot of users if left unchanged.

In short, users are presented with the option on the person form to add people to a locked post. If a user does this, a 403 is raised with no error message supplied.

At the moment, trusted (to lock) users don't get the error and untrusted users do. In either case, it's not helpful if you've mistakenly added a candidate to a locked ballot.

One option is to simply hide the locked ballots from the drop downs – this would stop errors, but would also be confusing if someone thought the data was missing. 

The better thing to do would be to disable the options and indicate they're locked. 

Do this this requires a bigger refactor of the forms than I'd planned, so I backed out of the work.
