### ISSUE TITLE
Missing candidates in past elections

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#994]
* https://candidates.democracyclub.org.uk/elections/local.guildford.shalford.2019-05-02/ - missing Bob Hughes (Conservative, 431 votes)
* https://candidates.democracyclub.org.uk/elections/local.guildford.ash-south-and-tongham.2019-05-02/ - missing Nigel James Kearse (Conservative, 817 votes)
* https://candidates.democracyclub.org.uk/elections/local.hartlepool.jesmond.2019-05-02/ - Linda Parker (Independent) should be Independent Union (PP7984)

**Comment by sjorford** [comment]
This is another with the wrong party: https://candidates.democracyclub.org.uk/person/61888/christine-cleveland

Should be Residents Associations of Epsom and Ewell (PP74)

SOPN
![image](https://user-images.githubusercontent.com/10633357/62956292-94536100-bdea-11e9-9b8b-cc64f99d659d.png)

Note that we have the wrong SOPN page attached to https://candidates.democracyclub.org.uk/elections/local.epsom-and-ewell.ewell.2019-05-02/

**Comment by symroe** [comment]
Do we think these missing candidates are human error when adding / locking, or that the ballot was correct but the memberships have been lost somehow?

**Comment by chris48s** [comment]
I think they're probably human error, as opposed to missing data: I don't think there's a bug that needs fixing.

The reason I've made a GH issue rather than just making edits via the front-end to fix the problem is because even if the posts are unlocked, we don't think its possible to add old elections to an existing person because elections which aren't 'current' don't appear in the dropdown list. As such, fixing them probably requires admin intervention/manual database fiddling at this point (unless you know of a way to do this).

Sorry - perhaps it would have been better to make a trello card instead of an issue as it is "a bit of work that needs doing" as opposed to "a bug that needs fixing", if you see what I mean.. although it might also be worth thinking about whether/how to allow these retrospective fixed to be made by users via the front-end at some point. I mainly just wanted to log this somewhere so it didn't disappear into the slack ether.

**Comment by symroe** [comment]
No that's cool – just hoping is wasn't a bug, as we've had problems with some combination of merging / reverting / whatever deleting memberships and other models in the past. That sort of bug is _really_ hard to debug (you have to guess what the conditions were before the models were deleted), so I'm glad it's just your standard human error :)

As for not being able to add a membership to an old ballot, yes, that can't be done anywhere apart from the shell / db I expect. I could make an interface for this but I'm not sure if it's worth it. I'll take a quick look at the admin interface and see if it's easy to do.
